# Generated by Django 5.2.6 on 2026-09-08 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('page_index', models.PositiveSmallIntegerField()),
                ('recognized_page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_key', models.CharField(max_length=320)),
                ('output_key', models.CharField(max_length=320)),
                ('source_sha256', models.CharField(max_length=64)),
                ('output_sha256', models.CharField(max_length=64)),
                ('recognition_artifact_key', models.CharField(blank=True, max_length=320)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('qr_code', models.CharField(blank=True, max_length=160)),
                ('is_blank', models.BooleanField(default=False)),
                ('is_supplement', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_wrong_page', models.BooleanField(default=False)),
                ('quality_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resolution_dpi', models.PositiveSmallIntegerField()),
                ('rotation_degrees', models.SmallIntegerField(default=0)),
                ('processing_metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['page_index'],
            },
        ),
        migrations.CreateModel(
            name='ScanQualityException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(max_length=40)),
                ('severity', models.CharField(default='medium', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('returned_scanning', 'Returned to scanning'), ('returned_verification', 'Returned to verification'), ('reprocessing', 'Reprocessing'), ('resolved', 'Resolved'), ('skipped', 'Skipped')], default='open', max_length=24)),
                ('reason', models.TextField()),
                ('resolution', models.TextField(blank=True)),
                ('resolved_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=120)),
                ('configuration', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code', 'version'), name='unique_processing_profile_version')],
            },
        ),
        migrations.CreateModel(
            name='ProcessingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('quality_review', 'Quality review'), ('passed', 'Passed'), ('failed', 'Failed'), ('returned', 'Returned'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('current_stage', models.CharField(default='page_detection', max_length=40)),
                ('source_digest', models.CharField(max_length=64)),
                ('output_digest', models.CharField(blank=True, max_length=64)),
                ('metrics', models.JSONField(default=dict)),
                ('recognition_summary', models.JSONField(default=dict)),
                ('skip_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='scan_processing.processingprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
