# Generated by Django 5.2.6 on 2026-09-08 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custody', '0002_script_bundle_barcode_script_centre_barcode_and_more'),
        ('scan_processing', '0001_initial'),
        ('scanning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingrun',
            name='scan_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_runs', to='scanning.scanjob'),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processing_runs', to='custody.script'),
        ),
        migrations.AddField(
            model_name='processedpage',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='scan_processing.processingrun'),
        ),
        migrations.AddField(
            model_name='scanqualityexception',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='scan_processing.processedpage'),
        ),
        migrations.AddField(
            model_name='scanqualityexception',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='scan_processing.processingrun'),
        ),
        migrations.AddConstraint(
            model_name='processedpage',
            constraint=models.UniqueConstraint(fields=('run', 'page_index'), name='unique_processed_run_page'),
        ),
    ]
