# Generated by Django 5.2.6 on 2026-09-07 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custody', '0001_initial'),
        ('evaluators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('valuation_round', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('expired', 'Expired'), ('reassigned', 'Reassigned')], default='assigned', max_length=16)),
                ('quality_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='evaluators.evaluator')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='custody.script')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('script', 'valuation_round'), name='unique_script_round')],
            },
        ),
    ]
