# Generated by Django 5.2.6 on 2026-09-07 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
        ('configuration', '0002_paper_effective_from_configurationrevision_and_more'),
        ('custody', '0002_script_bundle_barcode_script_centre_barcode_and_more'),
        ('evaluators', '0002_evaluator_email_evaluator_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='backup_evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backup_assignments', to='evaluators.evaluator'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='draft_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='last_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='last_page',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='priority',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='assignment',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignment',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assignment',
            name='skipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='source',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AllocationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('algorithm', models.CharField(choices=[('intelligent', 'Intelligent matching'), ('rules', 'Rules based'), ('random', 'Random')], default='intelligent', max_length=20)),
                ('minimum_experience_years', models.PositiveSmallIntegerField(default=2)),
                ('minimum_expertise_level', models.PositiveSmallIntegerField(default=2)),
                ('maximum_active_assignments', models.PositiveSmallIntegerField(default=20)),
                ('assignment_due_hours', models.PositiveSmallIntegerField(default=120)),
                ('backup_required', models.BooleanField(default=True)),
                ('allow_same_institution', models.BooleanField(default=False)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_policy', to='configuration.paper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('mode', models.CharField(choices=[('simulation', 'Simulation'), ('execution', 'Execution')], max_length=16)),
                ('algorithm', models.CharField(choices=[('intelligent', 'Intelligent matching'), ('rules', 'Rules based'), ('random', 'Random')], max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('partial', 'Partially completed'), ('failed', 'Failed')], default='planned', max_length=16)),
                ('requested_scripts', models.PositiveIntegerField(default=0)),
                ('planned_scripts', models.PositiveIntegerField(default=0)),
                ('allocated_scripts', models.PositiveIntegerField(default=0)),
                ('unallocated_scripts', models.PositiveIntegerField(default=0)),
                ('average_quality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('forecast', models.JSONField(default=dict)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_runs', to='configuration.paper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(max_length=40)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('from_evaluator_id', models.UUIDField(blank=True, null=True)),
                ('to_evaluator_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='allocation.assignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('valuation_round', models.PositiveSmallIntegerField(default=1)),
                ('quality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('blockers', models.JSONField(default=list)),
                ('backup_evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backup_allocation_proposals', to='evaluators.evaluator')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_proposals', to='evaluators.evaluator')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_proposals', to='custody.script')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='allocation.allocationrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'script', 'valuation_round'), name='unique_run_script_round_proposal')],
            },
        ),
    ]
