# Generated by Django 5.2.6 on 2026-09-07 14:03

import apps.identity_auth.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _alter_login_attempt_id(apps, schema_editor, *, to_uuid):
    login_attempt = apps.get_model("identity_auth", "LoginAttempt")
    old_field = login_attempt._meta.get_field("id")
    if to_uuid:
        new_field = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)
    else:
        new_field = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")
    new_field.set_attributes_from_name("id")
    new_field.model = login_attempt
    schema_editor.alter_field(login_attempt, old_field, new_field, strict=True)


def convert_login_attempt_id_to_uuid(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        _alter_login_attempt_id(apps, schema_editor, to_uuid=True)
        return

    table = schema_editor.quote_name("identity_auth_loginattempt")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"ALTER TABLE {table} ADD COLUMN id_uuid uuid")
        cursor.execute(f"UPDATE {table} SET id_uuid = gen_random_uuid()")
        cursor.execute(f"ALTER TABLE {table} DROP CONSTRAINT identity_auth_loginattempt_pkey")
        cursor.execute(f"ALTER TABLE {table} DROP COLUMN id")
        cursor.execute(f"ALTER TABLE {table} RENAME COLUMN id_uuid TO id")
        cursor.execute(f"ALTER TABLE {table} ALTER COLUMN id SET NOT NULL")
        cursor.execute(f"ALTER TABLE {table} ADD PRIMARY KEY (id)")


def convert_login_attempt_id_to_bigint(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        _alter_login_attempt_id(apps, schema_editor, to_uuid=False)
        return

    table = schema_editor.quote_name("identity_auth_loginattempt")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"ALTER TABLE {table} ADD COLUMN id_bigint bigserial")
        cursor.execute(f"ALTER TABLE {table} DROP CONSTRAINT identity_auth_loginattempt_pkey")
        cursor.execute(f"ALTER TABLE {table} DROP COLUMN id")
        cursor.execute(f"ALTER TABLE {table} RENAME COLUMN id_bigint TO id")
        cursor.execute(f"ALTER TABLE {table} ALTER COLUMN id SET NOT NULL")
        cursor.execute(f"ALTER TABLE {table} ADD PRIMARY KEY (id)")


class Migration(migrations.Migration):

    dependencies = [
        ('identity_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesssession',
            name='expires_at',
            field=models.DateTimeField(db_index=True, default=apps.identity_auth.models.default_session_expiry),
        ),
        migrations.AddField(
            model_name='accesssession',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='accesssession',
            name='mfa_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesssession',
            name='revoked_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='accesssession',
            name='risk_reasons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='accesssession',
            name='step_up_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='challenged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='device_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(convert_login_attempt_id_to_uuid, convert_login_attempt_id_to_bigint),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='loginattempt',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AuthenticationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event', models.CharField(db_index=True, max_length=80)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('challenged', 'Challenged'), ('revoked', 'Revoked')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_hash', models.CharField(blank=True, max_length=64)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_reasons', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OidcProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('issuer', models.URLField()),
                ('client_id', models.CharField(max_length=160)),
                ('client_secret_ciphertext', models.TextField()),
                ('scopes', models.CharField(default='openid email profile', max_length=255)),
                ('domain_hint', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'name'), name='unique_tenant_oidc_provider')],
            },
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('step_up', 'Step-up'), ('recovery', 'Recovery')], max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts_remaining', models.PositiveSmallIntegerField(default=5)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasskeyCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_id', models.BinaryField(unique=True)),
                ('public_key', models.BinaryField()),
                ('sign_count', models.PositiveBigIntegerField(default=0)),
                ('transports', models.JSONField(default=list)),
                ('device_type', models.CharField(blank=True, max_length=40)),
                ('backed_up', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=100)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkey_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_hash', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=100)),
                ('platform', models.CharField(blank=True, max_length=80)),
                ('browser', models.CharField(blank=True, max_length=80)),
                ('public_key', models.TextField(blank=True)),
                ('binding_signature', models.CharField(blank=True, max_length=128)),
                ('trusted_until', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accesssession',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='identity_auth.trusteddevice'),
        ),
        migrations.CreateModel(
            name='AuthenticationMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('totp', 'Authenticator'), ('email_otp', 'Email OTP'), ('passkey', 'Passkey')], max_length=24)),
                ('label', models.CharField(max_length=80)),
                ('secret_ciphertext', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'label'), name='unique_user_auth_method')],
            },
        ),
        migrations.AddConstraint(
            model_name='trusteddevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_hash'), name='unique_user_device'),
        ),
    ]
