# Generated by Django 5.2.6 on 2026-09-16 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_device_authorizations(apps, schema_editor):
    AccessSession = apps.get_model('identity_auth', 'AccessSession')
    DeviceAuthorization = apps.get_model('identity_auth', 'DeviceAuthorization')
    Membership = apps.get_model('tenancy', 'Membership')
    for session in AccessSession.objects.exclude(device_id__isnull=True).values('tenant_id', 'device_id', 'user_id').distinct().iterator():
        is_admin = Membership.objects.filter(
            user_id=session['user_id'],
            institution__tenant_id=session['tenant_id'],
            is_active=True,
            role__in=['platform_admin', 'university_admin'],
        ).exists()
        DeviceAuthorization.objects.get_or_create(
            tenant_id=session['tenant_id'],
            device_id=session['device_id'],
            defaults={'approved_at': timezone.now() if is_admin else None},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('identity_auth', '0003_accesssession_tenant_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_approvals', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='identity_auth.trusteddevice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'device'), name='unique_tenant_device_authorization')],
            },
        ),
        migrations.RunPython(backfill_device_authorizations, migrations.RunPython.noop),
    ]
