# Generated by Django 5.2.6 on 2026-09-07 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('evaluator_code', models.CharField(max_length=32)),
                ('display_name', models.CharField(max_length=120)),
                ('institution_name', models.CharField(max_length=180)),
                ('department', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('qualification', models.CharField(max_length=180)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('grade', models.CharField(choices=[('evaluator', 'Evaluator'), ('senior', 'Senior examiner'), ('chief', 'Chief examiner'), ('moderator', 'Moderator'), ('revaluator', 'Revaluator'), ('scrutinizer', 'Scrutinizer'), ('verifier', 'Verifier')], default='evaluator', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired')], default='pending', max_length=16)),
                ('daily_capacity', models.PositiveSmallIntegerField(default=20)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'evaluator_code'), name='unique_evaluator_code')],
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('verified', models.BooleanField(default=False)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='evaluators.evaluator')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluators', to='configuration.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('evaluator', 'subject'), name='unique_evaluator_subject')],
            },
        ),
    ]
