# Generated by Django 5.2.6 on 2026-09-07 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='employee_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='employment_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='employment_type',
            field=models.CharField(default='permanent', max_length=40),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='mobile',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='expertise',
            name='years_experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EvaluatorAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('daily_capacity', models.PositiveSmallIntegerField()),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_periods', to='evaluators.evaluator')),
            ],
            options={
                'ordering': ['starts_on'],
            },
        ),
        migrations.CreateModel(
            name='EvaluatorHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(blank=True, max_length=16)),
                ('from_grade', models.CharField(blank=True, max_length=20)),
                ('to_grade', models.CharField(blank=True, max_length=20)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='evaluators.evaluator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
