# Generated by Django 5.2.6 on 2026-09-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0005_evaluator_face_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='is_system_ai',
            field=models.BooleanField(default=False),
        ),
    ]
