"use client";

import { BookOpenCheck, Check, FileText, LockKeyhole, MessageSquareText, Plus, RefreshCw, Send, Trash2, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { DynamicFields, readDynamicFields, useDynamicFields } from "@/components/dynamic-fields";
import { csrfFetch } from "@/lib/api";

type Paper = { id: string; code: string; title: string; questions: { id: string; number: string; sub_question?: string; label?: string; max_marks: number }[] };
type Scheme = { id: string; paper_id: string; paper: string; title: string; version: number; status: string; guidelines: string; instructions: string; content_digest: string };
type Criterion = { id: string; scheme_id: string; question_id: string; question: string; code: string; description: string; max_marks: number; step_marks: number[]; tolerance: number; mandatory: boolean };
type Clarification = { id: string; scheme_id: string; question: string | null; scope: string; title: string; body: string; version: number; mandatory: boolean };
type Catalog = { papers: Paper[]; schemes: Scheme[]; criteria: Criterion[]; clarifications: Clarification[] };
const empty: Catalog = { papers: [], schemes: [], criteria: [], clarifications: [] };
const titleCase = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const questionLabel = (item: { number: string; sub_question?: string; label?: string }) => item.label || (item.sub_question ? `${item.number}(${item.sub_question})` : item.number);
async function api(path: string, options?: RequestInit) { const response = await csrfFetch(path, options); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || "Rubric operation failed"); return body; }

export function RubricWorkspace() {
  const [data, setData] = useState<Catalog>(empty); const [tab, setTab] = useState<"schemes" | "criteria" | "clarifications">("schemes"); const [modal, setModal] = useState<"scheme" | "criterion" | "clarification" | null>(null); const [selected, setSelected] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setBusy(true); try { const body = await api("/api/v1/rubrics/catalog"); setData(body); setSelected((value) => value || body.schemes[0]?.id || ""); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Rubrics could not be loaded"); } finally { setBusy(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const active = data.schemes.find((item) => item.id === selected); const criteria = data.criteria.filter((item) => item.scheme_id === selected); const clarifications = data.clarifications.filter((item) => item.scheme_id === selected);
  const activePaper = data.papers.find((item) => item.id === active?.paper_id);
  const questionTotals = activePaper?.questions.map((question) => {
    const total = criteria.filter((item) => item.question_id === question.id).reduce((sum, item) => sum + Number(item.max_marks), 0);
    return { question, total, complete: total === Number(question.max_marks) };
  }) || [];
  async function transition(item: Scheme, target: string) { setSelected(item.id); setBusy(true); try { await api(`/api/v1/rubrics/schemes/${item.id}/transition`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ target, reason: `Moved to ${target} after rubric review.` }) }); setNotice(`Scheme moved to ${titleCase(target)}`); await load(); } catch (reason) { setTab("criteria"); setError(reason instanceof Error ? reason.message : "Transition failed"); } finally { setBusy(false); } }
  async function deleteCriterion(item: Criterion) { if (!active || active.status !== "draft") return; setBusy(true); try { await api(`/api/v1/rubrics/schemes/${active.id}/criteria/${item.id}`, { method: "DELETE" }); setNotice("Criterion removed"); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not remove criterion"); } finally { setBusy(false); } }
  return <div className="config-workspace"><div className="receiving-summary"><div><BookOpenCheck /><span>Scheme versions</span><strong>{data.schemes.length}</strong></div><div><FileText /><span>Rubric criteria</span><strong>{data.criteria.length}</strong></div><div><MessageSquareText /><span>Clarifications</span><strong>{data.clarifications.length}</strong></div></div>
    <div className="workspace-toolbar"><div className="entity-tabs"><button className={tab === "schemes" ? "active" : ""} onClick={() => setTab("schemes")}>Schemes</button><button className={tab === "criteria" ? "active" : ""} onClick={() => setTab("criteria")}>Criteria</button><button className={tab === "clarifications" ? "active" : ""} onClick={() => setTab("clarifications")}>Clarifications</button></div><div className="header-actions"><select className="compact-select" value={selected} onChange={(event) => setSelected(event.target.value)}>{data.schemes.map((item) => <option value={item.id} key={item.id}>{item.paper} · v{item.version}</option>)}</select><button className="secondary-button" onClick={() => void load()} disabled={busy}><RefreshCw className={busy ? "spin" : undefined} />{busy ? "Refreshing" : "Refresh"}</button><button className="primary-button" onClick={() => setModal(tab === "schemes" ? "scheme" : tab === "criteria" ? "criterion" : "clarification")}><Plus />New</button></div></div>
    {notice && <div className="success-banner"><Check />{notice}</div>}{error && <div className="form-error">{error}</div>}
    {tab === "schemes" && <section className="panel"><header className="panel-header"><div><h2 className="panel-title">Scheme register</h2><p className="panel-subtitle">Versioned approval and freeze history</p></div></header><div className="table-wrap"><table><thead><tr><th>Paper</th><th>Scheme</th><th>Version</th><th>Guidance</th><th>Digest</th><th>Status</th><th>Control</th></tr></thead><tbody>{data.schemes.map((item) => <tr key={item.id}><td><strong>{item.paper}</strong></td><td>{item.title}</td><td>v{item.version}</td><td className="purpose-cell">{item.guidelines}</td><td><code className="hash-value">{item.content_digest ? `${item.content_digest.slice(0, 12)}…` : "Pending"}</code></td><td><span className={`status-pill ${item.status}`}>{titleCase(item.status)}</span></td><td><div className="row-actions">{item.status === "draft" && <button title="Submit for review" disabled={busy} onClick={() => transition(item, "review")}><Send /></button>}{item.status === "review" && <button title="Approve scheme" disabled={busy} onClick={() => transition(item, "approved")}><Check /></button>}{item.status === "approved" && <button title="Freeze scheme" disabled={busy} onClick={() => transition(item, "frozen")}><LockKeyhole /></button>}</div></td></tr>)}</tbody></table></div></section>}
    {tab === "criteria" && <section className="panel"><header className="panel-header"><div><h2 className="panel-title">Question criteria</h2><p className="panel-subtitle">Maximums, step marks, tolerance and mandatory evidence</p></div></header>{questionTotals.length > 0 && <div className="table-wrap"><table><thead><tr><th>Question</th><th>Required total</th><th>Criteria total</th><th>Status</th></tr></thead><tbody>{questionTotals.map(({ question, total, complete }) => <tr key={question.id}><td><strong>{questionLabel(question)}</strong></td><td>{question.max_marks}</td><td>{total}</td><td><span className={`status-pill ${complete ? "ready" : "attention"}`}>{complete ? "Complete" : `Add ${Number(question.max_marks) - total} marks`}</span></td></tr>)}</tbody></table></div>}<div className="table-wrap"><table><thead><tr><th>Question</th><th>Code</th><th>Description</th><th>Maximum</th><th>Steps</th><th>Tolerance</th><th>Required</th>{active?.status === "draft" && <th>Actions</th>}</tr></thead><tbody>{criteria.map((item) => <tr key={item.id}><td><strong>{item.question}</strong></td><td>{item.code}</td><td>{item.description}</td><td>{item.max_marks}</td><td>{item.step_marks.join(" · ") || "—"}</td><td>{item.tolerance}</td><td>{item.mandatory ? "Yes" : "No"}</td>{active?.status === "draft" && <td><button title="Remove criterion" disabled={busy} onClick={() => deleteCriterion(item)}><Trash2 /></button></td>}</tr>)}</tbody></table></div></section>}
    {tab === "clarifications" && <section className="panel"><header className="panel-header"><div><h2 className="panel-title">Published clarifications</h2><p className="panel-subtitle">Append-only question and subject guidance with acknowledgements</p></div></header><div className="table-wrap"><table><thead><tr><th>Scope</th><th>Question</th><th>Title</th><th>Clarification</th><th>Version</th><th>Acknowledgement</th></tr></thead><tbody>{clarifications.map((item) => <tr key={item.id}><td>{titleCase(item.scope)}</td><td>{item.question || "All"}</td><td><strong>{item.title}</strong></td><td>{item.body}</td><td>v{item.version}</td><td>{item.mandatory ? "Mandatory" : "Informational"}</td></tr>)}</tbody></table></div>{!clarifications.length && <div className="empty-state">No clarifications are published for this scheme.</div>}</section>}
    {modal && <RubricModal kind={modal} data={data} active={active} onClose={() => setModal(null)} onSaved={async () => { setModal(null); await load(); }} />}
  </div>;
}

function RubricModal({ kind, data, active, onClose, onSaved }: { kind: "scheme" | "criterion" | "clarification"; data: Catalog; active?: Scheme; onClose: () => void; onSaved: () => Promise<void> }) {
  const rubricFields = useDynamicFields("rubric");
  const paper = data.papers.find((item) => item.id === active?.paper_id) || data.papers[0]; const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { let path = "/api/v1/rubrics/schemes"; let body: object = { paper_id: form.get("paper"), title: form.get("title"), evaluation_guidelines: form.get("guidelines"), examiner_instructions: form.get("instructions"), partial_credit_rules: { enabled: true }, tolerance_rules: { rounding: "0.5" }, custom_fields: readDynamicFields(form, rubricFields) }; if (kind === "criterion") { path = `/api/v1/rubrics/schemes/${active?.id}/criteria`; body = { question_id: form.get("question"), code: form.get("code"), description: form.get("description"), max_marks: Number(form.get("max_marks")), step_marks: String(form.get("steps") || "").split(",").filter(Boolean).map(Number), tolerance: Number(form.get("tolerance")), is_mandatory: form.get("mandatory") === "on" }; } if (kind === "clarification") { path = `/api/v1/rubrics/schemes/${active?.id}/clarifications`; body = { question_id: form.get("question") || null, scope: form.get("scope"), title: form.get("title"), body: form.get("body"), mandatory_acknowledgement: form.get("mandatory") === "on" }; } await api(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); await onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save rubric item"); } finally { setBusy(false); } }
  return <div className="modal-backdrop"><form className="modal-panel" onSubmit={submit}><header className="modal-header"><div><h2>{kind === "scheme" ? "New scheme version" : kind === "criterion" ? "Add rubric criterion" : "Publish clarification"}</h2><p>Content remains traceable to this exact scheme version.</p></div><button type="button" className="icon-button" onClick={onClose}><X /></button></header><div className="form-grid">
    {kind === "scheme" ? <><label className="field"><span>Paper</span><select name="paper">{data.papers.map((item) => <option value={item.id} key={item.id}>{item.code}</option>)}</select></label><label className="field"><span>Title</span><input name="title" required /></label><label className="field full-field"><span>Evaluation guidelines</span><textarea name="guidelines" required /></label><label className="field full-field"><span>Examiner instructions</span><textarea name="instructions" required /></label><DynamicFields fields={rubricFields} /></> : kind === "criterion" ? <><label className="field"><span>Question</span><select name="question">{paper?.questions.map((item) => <option value={item.id} key={item.id}>{questionLabel(item)} · {item.max_marks} marks</option>)}</select></label><label className="field"><span>Criterion code</span><input name="code" required /></label><label className="field full-field"><span>Description</span><textarea name="description" required /></label><label className="field"><span>Maximum marks</span><input name="max_marks" type="number" step="0.5" required /></label><label className="field"><span>Step marks</span><input name="steps" placeholder="5,10,15,20" /></label><label className="field"><span>Tolerance</span><input name="tolerance" type="number" step="0.5" defaultValue="0" /></label><label className="check-field"><input name="mandatory" type="checkbox"/><span>Mandatory criterion</span></label></> : <><label className="field"><span>Scope</span><select name="scope"><option value="question">Question</option><option value="subject">Subject</option><option value="official">Official</option></select></label><label className="field"><span>Question</span><select name="question"><option value="">All questions</option>{paper?.questions.map((item) => <option value={item.id} key={item.id}>{questionLabel(item)}</option>)}</select></label><label className="field"><span>Title</span><input name="title" required /></label><label className="field full-field"><span>Clarification</span><textarea name="body" required /></label><label className="check-field"><input name="mandatory" type="checkbox"/><span>Require acknowledgement</span></label></>}{error && <div className="form-error full-field">{error}</div>}</div><footer className="modal-footer"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? "Saving" : "Save"}</button></footer></form></div>;
}
