"use client";

import { AlertTriangle, Check, GitCompareArrows, LockKeyhole, RefreshCw, Scale, ShieldCheck, X } from "lucide-react";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { csrfFetch } from "@/lib/api";

type Valuation = { results: { id: string; script: string; round: number; total_marks: number; checksum: string; locked: boolean; locked_at: string | null }[]; comparisons: { id: string; script: string; first: number; second: number; third: number | null; difference: number; percentage_difference: number; threshold: number; status: string; requires_third: boolean; question_differences: Record<string, { marks: string[]; difference: string }> }[]; final_marks: { id: string; script: string; mark: number; rule: string; status: string; checksum: string; version: number }[]; reveals: unknown[] };
type Discrepancies = { cases: { id: string; comparison_id: string; script: string; status: string; threshold: number; difference: number; items: { key: string; marks: string[]; difference: string }[]; assigned_role: string; version: number }[]; clarifications: { id: string; case_id: string; round: number; request: string; response: string; responded_at: string | null }[]; resolutions: { id: string; case_id: string; method: string; final_mark: number; reason: string; approved: boolean }[] };
const empty: Valuation = { results: [], comparisons: [], final_marks: [], reveals: [] }; const emptyDiscrepancies: Discrepancies = { cases: [], clarifications: [], resolutions: [] };
const title = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
async function api(path: string, options?: RequestInit) { const response = await csrfFetch(path, options); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || "Valuation operation failed"); return body; }

export function ValuationWorkspace() {
  const [tab, setTab] = useState<"rounds" | "comparisons" | "discrepancies" | "final">("comparisons"); const [valuation, setValuation] = useState<Valuation>(empty); const [discrepancies, setDiscrepancies] = useState<Discrepancies>(emptyDiscrepancies); const [resolve, setResolve] = useState<Discrepancies["cases"][number] | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setBusy(true); try { const [v, d] = await Promise.all([api("/api/v1/valuation/catalog"), api("/api/v1/discrepancy/catalog")]); setValuation(v); setDiscrepancies(d); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Valuation data could not be loaded"); } finally { setBusy(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function action(path: string, body?: object) { setBusy(true); try { await api(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: body ? JSON.stringify(body) : undefined }); setNotice("Valuation decision recorded successfully"); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Decision failed"); } finally { setBusy(false); } }
  const discrepanciesOpen = discrepancies.cases.filter((item) => !["resolved", "approved"].includes(item.status)).length; const third = valuation.comparisons.filter((item) => item.requires_third).length; const locked = valuation.final_marks.filter((item) => item.status === "locked").length;
  return <div className="config-workspace"><div className="receiving-summary"><div><GitCompareArrows /><span>Compared scripts</span><strong>{valuation.comparisons.length}</strong></div><div><AlertTriangle /><span>Open discrepancies</span><strong>{discrepanciesOpen + third}</strong></div><div><LockKeyhole /><span>Final marks locked</span><strong>{locked}</strong></div></div>
    <div className="workspace-toolbar"><div className="entity-tabs"><button className={tab === "rounds" ? "active" : ""} onClick={() => setTab("rounds")}>Blind rounds</button><button className={tab === "comparisons" ? "active" : ""} onClick={() => setTab("comparisons")}>Comparisons</button><button className={tab === "discrepancies" ? "active" : ""} onClick={() => setTab("discrepancies")}>Reconciliation</button><button className={tab === "final" ? "active" : ""} onClick={() => setTab("final")}>Final marks</button></div><button className="secondary-button" disabled={busy} onClick={load}><RefreshCw />Refresh</button></div>
    {notice && <div className="success-banner"><Check />{notice}</div>}{error && <div className="form-error">{error}</div>}
    {tab === "rounds" && <section className="panel"><header className="panel-header"><div><h2 className="panel-title">Independent valuation results</h2><p className="panel-subtitle">Locked round outputs become visible here only after submission</p></div></header><div className="table-wrap"><table><thead><tr><th>Anonymous script</th><th>Round</th><th>Total</th><th>Checksum</th><th>Locked at</th><th>Status</th></tr></thead><tbody>{valuation.results.map((item) => <tr key={item.id}><td><strong>{item.script}</strong></td><td>{item.round}</td><td>{item.total_marks}</td><td><code className="hash-value">{item.checksum.slice(0, 14)}…</code></td><td>{item.locked_at ? new Date(item.locked_at).toLocaleString("en-IN") : "—"}</td><td><span className={`status-pill ${item.locked ? "approved" : "review"}`}>{item.locked ? "Locked" : "Pending"}</span></td></tr>)}</tbody></table></div></section>}
    {tab === "comparisons" && <section className="panel"><header className="panel-header"><div><h2 className="panel-title">Threshold comparison</h2><p className="panel-subtitle">Question and total differences against the paper configuration</p></div></header><div className="table-wrap"><table><thead><tr><th>Script</th><th>Round 1</th><th>Round 2</th><th>Round 3</th><th>Difference</th><th>Threshold</th><th>Status</th></tr></thead><tbody>{valuation.comparisons.map((item) => <tr key={item.id}><td><strong>{item.script}</strong></td><td>{item.first}</td><td>{item.second}</td><td>{item.third ?? "—"}</td><td>{item.difference} <small>({item.percentage_difference}%)</small></td><td>{item.threshold}</td><td><span className={`status-pill ${item.status}`}>{title(item.status)}</span></td></tr>)}</tbody></table></div>{!valuation.comparisons.length && <div className="empty-state">Comparisons appear automatically after the second locked valuation.</div>}</section>}
    {tab === "discrepancies" && <><section className="panel"><header className="panel-header"><div><h2 className="panel-title">Discrepancy queue</h2><p className="panel-subtitle">Moderator, chief examiner and third-valuation routing</p></div></header><div className="table-wrap"><table><thead><tr><th>Script</th><th>Difference</th><th>Threshold</th><th>Items</th><th>Assigned role</th><th>Status</th><th>Control</th></tr></thead><tbody>{discrepancies.cases.map((item) => <tr key={item.id}><td><strong>{item.script}</strong></td><td>{item.difference}</td><td>{item.threshold}</td><td>{item.items.length}</td><td>{title(item.assigned_role)}</td><td><span className={`status-pill ${item.status}`}>{title(item.status)}</span></td><td><div className="row-actions">{!["resolved", "approved", "third_requested"].includes(item.status) && <button title="Resolve discrepancy" onClick={() => setResolve(item)}><Scale /></button>}{item.status === "open" && <button title="Route to chief examiner" onClick={() => action(`/api/v1/discrepancy/cases/${item.id}/route`, { version: item.version, target: "chief_examiner", role: "chief_examiner" })}><ShieldCheck /></button>}</div></td></tr>)}</tbody></table></div></section>
      {discrepancies.resolutions.length > 0 && <section className="panel"><header className="panel-header"><div><h2 className="panel-title">Resolution approvals</h2><p className="panel-subtitle">Independent approval is required before final mark lock</p></div></header><div className="table-wrap"><table><thead><tr><th>Method</th><th>Final mark</th><th>Reason</th><th>Status</th><th>Control</th></tr></thead><tbody>{discrepancies.resolutions.map((item) => <tr key={item.id}><td>{title(item.method)}</td><td><strong>{item.final_mark}</strong></td><td>{item.reason}</td><td>{item.approved ? "Approved" : "Pending approval"}</td><td><div className="row-actions">{!item.approved && <button title="Approve resolution" onClick={() => action(`/api/v1/discrepancy/resolutions/${item.id}/approve`)}><Check /></button>}</div></td></tr>)}</tbody></table></div></section>}</>}
    {tab === "final" && <section className="panel"><header className="panel-header"><div><h2 className="panel-title">Final mark register</h2><p className="panel-subtitle">Propose, independently approve, then irreversibly lock</p></div></header><div className="table-wrap"><table><thead><tr><th>Script</th><th>Mark</th><th>Rule</th><th>Checksum</th><th>Status</th><th>Control</th></tr></thead><tbody>{valuation.final_marks.map((item) => <tr key={item.id}><td><strong>{item.script}</strong></td><td>{item.mark}</td><td>{title(item.rule)}</td><td><code className="hash-value">{item.checksum ? `${item.checksum.slice(0, 14)}…` : "Pending lock"}</code></td><td><span className={`status-pill ${item.status}`}>{title(item.status)}</span></td><td><div className="row-actions">{item.status === "proposed" && <button title="Approve final mark" onClick={() => action(`/api/v1/valuation/final-marks/${item.id}/approve`, { version: item.version })}><Check /></button>}{item.status === "approved" && <button title="Lock final mark" onClick={() => action(`/api/v1/valuation/final-marks/${item.id}/lock`, { version: item.version })}><LockKeyhole /></button>}</div></td></tr>)}</tbody></table></div></section>}
    {resolve && <ResolutionModal item={resolve} onClose={() => setResolve(null)} onSaved={async () => { setResolve(null); await load(); }} />}
  </div>;
}

function ResolutionModal({ item, onClose, onSaved }: { item: Discrepancies["cases"][number]; onClose: () => void; onSaved: () => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { await api(`/api/v1/discrepancy/cases/${item.id}/resolve`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ version: item.version, method: form.get("method"), final_mark: Number(form.get("mark")), reason: form.get("reason"), calculation: { source: "moderator_decision" } }) }); await onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Resolution failed"); } finally { setBusy(false); } }
  return <div className="modal-backdrop"><form className="modal-panel" onSubmit={submit}><header className="modal-header"><div><h2>Resolve discrepancy</h2><p>{item.script} · difference {item.difference}, threshold {item.threshold}</p></div><button type="button" className="icon-button" onClick={onClose}><X /></button></header><div className="form-grid"><label className="field"><span>Method</span><select name="method"><option value="manual">Manual</option><option value="rule_based">Rule based</option><option value="override">Override</option></select></label><label className="field"><span>Final mark</span><input name="mark" type="number" step="0.5" min="0" required /></label><label className="field full-field"><span>Decision rationale</span><textarea name="reason" minLength={8} required /></label>{error && <div className="form-error full-field">{error}</div>}</div><footer className="modal-footer"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>Record resolution</button></footer></form></div>;
}
