# Generated by Django 5.2.6 on 2026-09-07 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='institution',
            name='code',
            field=models.SlugField(max_length=40),
        ),
        migrations.AlterField(
            model_name='institution',
            name='tenant_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='unique_tenant_institution_code'),
        ),
    ]
