# Generated by Django 5.2.6 on 2026-09-08 09:02

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


def create_accounts_for_existing_tenants(apps, schema_editor):
    Institution = apps.get_model("tenancy", "Institution")
    TenantAccount = apps.get_model("tenancy", "TenantAccount")
    TenantDomain = apps.get_model("tenancy", "TenantDomain")
    for root in Institution.objects.filter(parent__isnull=True).order_by("created_at"):
        slug = root.code.removesuffix("-university")[:63]
        if TenantAccount.objects.filter(slug=slug).exists():
            slug = f"{root.code[:54]}-{str(root.tenant_id)[:8]}"
        account = TenantAccount.objects.create(
            root_institution=root,
            slug=slug,
            status="active" if root.is_active else "suspended",
            enabled_modules=["configuration", "evaluators", "receiving", "custody", "digitization", "anonymisation", "repository", "allocation", "assignment_governance", "rubrics", "evaluation", "valuation", "assessment", "operations", "services", "security", "audit", "enterprise"],
        )
        TenantDomain.objects.create(
            tenant_account=account,
            hostname=f"{slug}.{settings.TENANT_BASE_DOMAIN}",
            kind="managed",
            status="active",
            is_primary=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_institution_version_alter_institution_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TenantAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('suspended', 'Suspended'), ('offboarding', 'Offboarding')], default='provisioning', max_length=20)),
                ('plan', models.CharField(choices=[('standard', 'Standard'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='standard', max_length=20)),
                ('enabled_modules', models.JSONField(default=list)),
                ('storage_quota_bytes', models.PositiveBigIntegerField(default=10737418240)),
                ('data_region', models.CharField(default='in-primary', max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('root_institution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_account', to='tenancy.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(max_length=253)),
                ('kind', models.CharField(choices=[('managed', 'Managed subdomain'), ('custom', 'Custom domain')], default='managed', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('active', 'Active'), ('failed', 'Verification failed')], default='pending', max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('tenant_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenancy.tenantaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('hostname'), name='unique_tenant_domain_hostname_ci')],
            },
        ),
        migrations.RunPython(create_accounts_for_existing_tenants, migrations.RunPython.noop),
    ]
