# Generated by Django 5.2.6 on 2026-09-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0011_restore_privileged_membership_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantaccount',
            name='brand_description',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='brand_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='brand_theme',
            field=models.CharField(choices=[('forest', 'Forest'), ('ocean', 'Ocean'), ('ruby', 'Ruby'), ('graphite', 'Graphite')], default='forest', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='logo_mime_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='tenantaccount',
            name='logo_storage_key',
            field=models.CharField(blank=True, max_length=320),
        ),
    ]
