# Generated by Django 5.2.6 on 2026-09-08 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocation', '0002_assignment_accepted_at_assignment_backup_evaluator_and_more'),
        ('configuration', '0003_configurationchangerequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('examiner', 'Examiner'), ('question', 'Question'), ('page', 'Page'), ('remark', 'Evaluation remark')], max_length=16)),
                ('body', models.TextField()),
                ('actor_id', models.PositiveBigIntegerField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('sub_question', models.CharField(blank=True, max_length=24)),
                ('sequence', models.PositiveIntegerField()),
                ('marks', models.DecimalField(decimal_places=2, max_digits=8)),
                ('outcome', models.CharField(choices=[('evaluated', 'Evaluated'), ('unanswered', 'Unanswered'), ('not_applicable', 'Not applicable'), ('skipped', 'Skipped')], default='evaluated', max_length=20)),
                ('adjustment', models.CharField(choices=[('none', 'None'), ('grace', 'Grace'), ('negative', 'Negative'), ('bonus', 'Bonus')], default='none', max_length=16)),
                ('step_marks', models.JSONField(default=list)),
                ('marked_for_review', models.BooleanField(default=False)),
                ('requires_attention', models.BooleanField(default=False)),
                ('examiner_confirmed', models.BooleanField(default=False)),
                ('answer_selection', models.JSONField(default=dict)),
                ('actor_id', models.PositiveBigIntegerField()),
            ],
            options={
                'ordering': ['question__position', 'sub_question', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('tick', 'Tick'), ('cross', 'Cross'), ('underline', 'Underline'), ('highlight', 'Highlight'), ('circle', 'Circle'), ('rectangle', 'Rectangle'), ('arrow', 'Arrow'), ('freehand', 'Freehand'), ('symbol', 'Symbol')], max_length=16)),
                ('action', models.CharField(choices=[('add', 'Add'), ('delete', 'Delete'), ('restore', 'Restore')], default='add', max_length=16)),
                ('geometry', models.JSONField(default=dict)),
                ('style', models.JSONField(default=dict)),
                ('symbol', models.CharField(blank=True, max_length=80)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='configuration.question')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history_events', to='marking.annotation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('submitted', 'Submitted'), ('locked', 'Locked')], default='draft', max_length=16)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('last_page', models.PositiveSmallIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation', to='allocation.assignment')),
                ('last_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_opened_evaluations', to='configuration.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
