# Generated by Django 5.2.6 on 2026-09-08 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0003_configurationchangerequest_and_more'),
        ('marking', '0001_initial'),
        ('rubrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='rubrics.markingscheme'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='marking.evaluation'),
        ),
        migrations.AddField(
            model_name='evaluationcomment',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='marking.evaluation'),
        ),
        migrations.AddField(
            model_name='evaluationcomment',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_comments', to='configuration.question'),
        ),
        migrations.AddField(
            model_name='questionmark',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_marks', to='marking.evaluation'),
        ),
        migrations.AddField(
            model_name='questionmark',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='configuration.question'),
        ),
        migrations.AddField(
            model_name='questionmark',
            name='rubric_criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='rubrics.rubriccriterion'),
        ),
        migrations.AddField(
            model_name='questionmark',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='marking.questionmark'),
        ),
        migrations.AddConstraint(
            model_name='questionmark',
            constraint=models.UniqueConstraint(fields=('evaluation', 'question', 'sub_question', 'sequence'), name='unique_question_mark_revision'),
        ),
    ]
