# Generated by Django 5.2.6 on 2026-09-16 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_subject_course_subject_related_subject_ids_and_more'),
        ('marking', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPageAnchor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('actor_id', models.PositiveBigIntegerField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_anchors', to='marking.evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_anchors', to='configuration.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('evaluation', 'question'), name='unique_question_page_anchor')],
            },
        ),
    ]
