# Generated by Django 5.2.6 on 2026-09-08 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocation', '0002_assignment_accepted_at_assignment_backup_evaluator_and_more'),
        ('configuration', '0003_configurationchangerequest_and_more'),
        ('evaluators', '0003_alter_evaluator_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentGovernancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('approval_required', models.BooleanField(default=True)),
                ('assignment_expiry_hours', models.PositiveSmallIntegerField(default=120)),
                ('lock_minutes', models.PositiveSmallIntegerField(default=30)),
                ('require_step_up_for_reassignment', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_governance', to='configuration.paper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecureReassignmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed'), ('expired', 'Expired')], default='requested', max_length=16)),
                ('requested_by_id', models.PositiveBigIntegerField()),
                ('decided_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secure_reassignments', to='allocation.assignment')),
                ('proposed_evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposed_reassignments', to='evaluators.evaluator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('note', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_approvals', to='allocation.assignment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assignment', 'actor_id'), name='unique_assignment_approval_actor')],
            },
        ),
        migrations.CreateModel(
            name='AssignmentLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, max_length=120)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_locks', to='allocation.assignment')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_locks', to='evaluators.evaluator')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('assignment',), name='one_active_assignment_lock')],
            },
        ),
    ]
