# Generated by Django 5.2.6 on 2026-09-08 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('identity_auth', '0003_accesssession_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentlock',
            name='access_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_locks', to='identity_auth.accesssession'),
        ),
    ]
