# Generated by Django 5.2.6 on 2026-09-07 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0002_paper_effective_from_configurationrevision_and_more'),
        ('evaluators', '0002_evaluator_email_evaluator_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('eligible', 'Eligible'), ('ineligible', 'Ineligible'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('qualification_ok', models.BooleanField(default=False)),
                ('experience_ok', models.BooleanField(default=False)),
                ('institution_ok', models.BooleanField(default=False)),
                ('expertise_ok', models.BooleanField(default=False)),
                ('has_conflict', models.BooleanField(default=False)),
                ('is_debarred', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('risk_reasons', models.JSONField(default=list)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('approved_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_records', to='evaluators.evaluator')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_records', to='configuration.subject')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(max_length=40)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('eligibility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='eligibility.eligibilityrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=16)),
                ('checks', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('evaluator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verification', to='evaluators.evaluator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(max_length=40)),
                ('storage_key', models.CharField(max_length=320, unique=True)),
                ('sha256', models.CharField(max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='eligibility.verificationcase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='eligibilityrecord',
            constraint=models.UniqueConstraint(fields=('evaluator', 'subject'), name='unique_evaluator_subject_eligibility'),
        ),
    ]
