# Generated by Django 5.2.6 on 2026-09-07 16:30

import apps.eligibility.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcase',
            name='fraud_signals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='verificationcase',
            name='required_approvals',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='verificationcase',
            name='revalidation_due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationcase',
            name='submitted_by_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='byte_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='expires_at',
            field=models.DateTimeField(default=apps.eligibility.models.default_document_expiry),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='maximum_bytes',
            field=models.PositiveIntegerField(default=10000000),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='mime_type',
            field=models.CharField(default='application/pdf', max_length=100),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending upload'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='verificationdocument',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='VerificationApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('approver_id', models.PositiveBigIntegerField()),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='eligibility.verificationcase')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('verification', 'approver_id'), name='unique_verification_approver'), models.UniqueConstraint(fields=('verification', 'level'), name='unique_verification_approval_level')],
            },
        ),
    ]
