# Generated by Django 5.2.6 on 2026-09-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_idempotencyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
