# Generated by Django 5.2.6 on 2026-09-07 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('reference', models.CharField(max_length=40)),
                ('source_centre', models.CharField(max_length=120)),
                ('expected_packets', models.PositiveIntegerField()),
                ('expected_scripts', models.PositiveIntegerField()),
                ('received_packets', models.PositiveIntegerField(default=0)),
                ('received_scripts', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('in_transit', 'In transit'), ('received', 'Received'), ('reconciled', 'Reconciled'), ('exception', 'Exception'), ('closed', 'Closed')], default='registered', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='configuration.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('expected_scripts', models.PositiveIntegerField()),
                ('received_scripts', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(default='intact', max_length=20)),
                ('status', models.CharField(default='registered', max_length=20)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packets', to='receiving.dispatch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceivingException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('damaged', 'Damaged script'), ('torn', 'Torn script'), ('wet', 'Wet script'), ('loose_page', 'Loose page'), ('missing_supplement', 'Missing supplement'), ('unidentified', 'Unidentified script'), ('discrepancy', 'Physical discrepancy')], max_length=28)),
                ('notes', models.TextField(blank=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='receiving.dispatch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='dispatch',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'reference'), name='unique_dispatch_ref'),
        ),
    ]
