# Generated by Django 5.2.6 on 2026-09-07 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='carrier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='expected_arrival_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='manifest_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='manifest_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatches_registered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatches_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packet',
            name='handed_over_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='packet',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packet',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packets_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packet',
            name='seal_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='packet',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='receivingexception',
            name='packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='receiving.packet'),
        ),
        migrations.AddField(
            model_name='receivingexception',
            name='reconciliation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='receivingexception',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivingexception',
            name='script_barcode',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='receivingexception',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='receivingexception',
            name='supervisor_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivingexception',
            name='supervisor_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='receivingexception',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('expected_scripts', models.PositiveIntegerField()),
                ('received_scripts', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(default='intact', max_length=20)),
                ('status', models.CharField(default='registered', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundles', to='receiving.packet')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bundles_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='receivingexception',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='receiving.bundle'),
        ),
        migrations.CreateModel(
            name='ReceiptConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('confirmation_type', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiving_confirmations', to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='receiving.dispatch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReceivingAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('transit_delay', 'Transit delay'), ('unreceived_packet', 'Unreceived packet'), ('count_mismatch', 'Count mismatch')], max_length=28)),
                ('message', models.CharField(max_length=240)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='receiving.dispatch')),
                ('packet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='receiving.packet')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('acknowledged_at__isnull', True)), fields=('dispatch', 'packet', 'kind'), name='unique_open_receiving_alert')],
            },
        ),
    ]
