# Generated by Django 5.2.6 on 2026-09-18 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_calendaroverlapexception'),
        ('receiving', '0002_dispatch_carrier_dispatch_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='intake_mode',
            field=models.CharField(choices=[('legacy', 'Legacy receiving'), ('transfer', 'Transfer to university'), ('on_site', 'Scan on site')], default='legacy', max_length=16),
        ),
        migrations.AddField(
            model_name='packet',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_packets', to='configuration.paper'),
        ),
        migrations.AddField(
            model_name='packet',
            name='script_manifest',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
