# Generated by Django 5.2.6 on 2026-09-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0003_dispatch_intake_mode_packet_paper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('in_transit', 'In transit'), ('on_site', 'On-site scanning'), ('received', 'Received'), ('reconciled', 'Reconciled'), ('exception', 'Exception'), ('closed', 'Closed')], default='registered', max_length=16),
        ),
    ]
