# Generated by Django 5.2.6 on 2026-09-25 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_paper_frozen_by_id'),
        ('receiving', '0004_alter_dispatch_status'),
        ('tenancy', '0012_tenantaccount_brand_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='source_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_dispatches', to='tenancy.institution'),
        ),
        migrations.CreateModel(
            name='PreparedPacket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('script_manifest', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('ready', 'Ready for bundling'), ('bundled', 'Bundled')], default='ready', max_length=16)),
                ('bundled_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('packet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparation', to='receiving.packet')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_intake_packets', to='configuration.paper')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_intake_packets', to=settings.AUTH_USER_MODEL)),
                ('source_college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_intake_packets', to='tenancy.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
