# Generated by Django 5.2.6 on 2026-09-07 15:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custody', '0002_script_bundle_barcode_script_centre_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('identity_reference', models.UUIDField(db_index=True, unique=True)),
                ('linked_by_id', models.PositiveBigIntegerField()),
                ('stored_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='identity_link', to='custody.script')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityResolutionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('requested_by_id', models.PositiveBigIntegerField()),
                ('purpose', models.CharField(max_length=160)),
                ('emergency', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('consumed', 'Consumed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('identity_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolution_requests', to='anonymisation.identitylink')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaskingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('profile', models.CharField(default='university-standard-v1', max_length=80)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('reviewed', 'Reviewed'), ('processing', 'Processing'), ('applied', 'Applied'), ('verified', 'Verified'), ('failed', 'Failed')], default='detected', max_length=20)),
                ('detection_confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('reviewed_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('applied_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('verified_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='masking_jobs', to='custody.script')),
            ],
        ),
        migrations.CreateModel(
            name='MaskRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('candidate_name', 'Candidate name'), ('register_number', 'Register number'), ('usn', 'USN'), ('college', 'College'), ('institution', 'Institution'), ('signature', 'Signature'), ('photograph', 'Photograph')], max_length=24)),
                ('x', models.DecimalField(decimal_places=6, max_digits=7)),
                ('y', models.DecimalField(decimal_places=6, max_digits=7)),
                ('width', models.DecimalField(decimal_places=6, max_digits=7)),
                ('height', models.DecimalField(decimal_places=6, max_digits=7)),
                ('source', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='anonymisation.maskingjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaskVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('verifier_id', models.PositiveBigIntegerField()),
                ('passed', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='anonymisation.maskingjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityResolutionApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('approver_id', models.PositiveBigIntegerField()),
                ('approved', models.BooleanField()),
                ('note', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='anonymisation.identityresolutionrequest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('request', 'approver_id'), name='one_identity_resolution_decision_per_approver')],
            },
        ),
        migrations.AddConstraint(
            model_name='maskingjob',
            constraint=models.UniqueConstraint(fields=('script', 'version'), name='unique_script_masking_job_version'),
        ),
    ]
