# Generated by Django 5.2.6 on 2026-09-21 10:37

from django.db import migrations, models


def use_assistant_model_alias(apps, schema_editor):
    SecurityPolicy = apps.get_model("security", "SecurityPolicy")
    SecurityPolicy.objects.update(ai_model_name="admiezo-ai-v1")


def restore_provider_model_name(apps, schema_editor):
    SecurityPolicy = apps.get_model("security", "SecurityPolicy")
    SecurityPolicy.objects.filter(ai_model_name="admiezo-ai-v1").update(ai_model_name="gemini-2.5-flash")


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_securitypolicy_ai_governance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitypolicy',
            name='ai_model_name',
            field=models.CharField(default='admiezo-ai-v1', max_length=80),
        ),
        migrations.RunPython(use_assistant_model_alias, restore_provider_model_name),
    ]
