# Generated by Django 5.2.6 on 2026-09-07 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('identity_reference', models.UUIDField(db_index=True, unique=True)),
                ('script_id', models.UUIDField(db_index=True, unique=True)),
                ('session_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('pii_ciphertext', models.TextField()),
                ('register_number_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumedAuthorization',
            fields=[
                ('jti', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('identity_reference', models.UUIDField(db_index=True)),
                ('action', models.CharField(max_length=40)),
                ('authorization_id', models.CharField(max_length=64)),
                ('actor_id', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=160)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
