# Generated by Django 5.2.6 on 2026-09-08 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0003_configurationchangerequest_and_more'),
        ('evaluators', '0003_alter_evaluator_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=180)),
                ('evaluation_guidelines', models.TextField()),
                ('examiner_instructions', models.TextField()),
                ('model_answer_key', models.CharField(blank=True, max_length=320)),
                ('suggested_answer_key', models.CharField(blank=True, max_length=320)),
                ('subject_rules', models.JSONField(default=dict)),
                ('regulation_rules', models.JSONField(default=dict)),
                ('partial_credit_rules', models.JSONField(default=dict)),
                ('tolerance_rules', models.JSONField(default=dict)),
                ('special_rules', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('approved', 'Approved'), ('frozen', 'Frozen'), ('superseded', 'Superseded')], default='draft', max_length=16)),
                ('content_digest', models.CharField(blank=True, max_length=64)),
                ('created_by_id', models.PositiveBigIntegerField()),
                ('approved_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marking_schemes', to='configuration.paper')),
            ],
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=7)),
                ('step_marks', models.JSONField(default=list)),
                ('partial_credit_rule', models.JSONField(default=dict)),
                ('tolerance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_criteria', to='configuration.question')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criteria', to='rubrics.markingscheme')),
            ],
            options={
                'ordering': ['question__position', 'position'],
            },
        ),
        migrations.CreateModel(
            name='SchemeClarification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('scope', models.CharField(choices=[('question', 'Question'), ('subject', 'Subject'), ('official', 'Official')], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('mandatory_acknowledgement', models.BooleanField(default=False)),
                ('published_by_id', models.PositiveBigIntegerField()),
                ('published_at', models.DateTimeField()),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clarifications', to='configuration.question')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clarifications', to='rubrics.markingscheme')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='rubrics.schemeclarification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructionAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('content_digest', models.CharField(max_length=64)),
                ('acknowledged_at', models.DateTimeField()),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instruction_acknowledgements', to='evaluators.evaluator')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='rubrics.markingscheme')),
                ('clarification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='rubrics.schemeclarification')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(max_length=32)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='rubrics.markingscheme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='markingscheme',
            constraint=models.UniqueConstraint(fields=('paper', 'version'), name='unique_paper_scheme_version'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('scheme', 'question', 'code'), name='unique_scheme_question_criterion'),
        ),
        migrations.AddConstraint(
            model_name='instructionacknowledgement',
            constraint=models.UniqueConstraint(fields=('scheme', 'evaluator', 'clarification'), name='unique_instruction_acknowledgement'),
        ),
    ]
