# Generated by Django 5.2.6 on 2026-09-07 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custody', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('master', 'Immutable master'), ('evaluation', 'Evaluation copy'), ('thumbnail', 'Thumbnail')], max_length=16)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('storage_key', models.CharField(max_length=320, unique=True)),
                ('sha256', models.CharField(max_length=64)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('mime_type', models.CharField(default='image/webp', max_length=64)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('retention_until', models.DateField(blank=True, null=True)),
                ('legal_hold', models.BooleanField(default=False)),
                ('integrity_checked_at', models.DateTimeField(blank=True, null=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='custody.script')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('script', 'kind', 'page_number', 'version'), name='unique_asset_version')],
            },
        ),
    ]
