# Generated by Django 5.2.6 on 2026-09-07 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0002_script_bundle_barcode_script_centre_barcode_and_more'),
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('raw_scan', 'Raw scan'), ('master', 'Immutable master'), ('evaluation', 'Evaluation copy'), ('thumbnail', 'Thumbnail')], max_length=16)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('storage_key', models.CharField(max_length=320, unique=True)),
                ('content_type', models.CharField(max_length=64)),
                ('maximum_bytes', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('completed', 'Completed'), ('expired', 'Expired')], default='issued', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_intents', to='custody.script')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'completed')), fields=('script', 'kind', 'page_number'), name='one_completed_upload_per_script_kind_page')],
            },
        ),
    ]
