# Generated by Django 5.2.6 on 2026-09-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0002_script_bundle_barcode_script_centre_barcode_and_more'),
        ('repository', '0002_uploadintent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uploadintent',
            name='one_completed_upload_per_script_kind_page',
        ),
        migrations.AddField(
            model_name='scriptasset',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scriptasset',
            name='backup_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='scriptasset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scriptasset',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scriptasset',
            name='object_lock_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scriptasset',
            name='replication_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadintent',
            name='asset_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='uploadintent',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'completed')), fields=('script', 'kind', 'page_number', 'asset_version'), name='one_completed_upload_per_script_kind_page'),
        ),
    ]
