# Generated by Django 5.2.6 on 2026-09-08 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allocation', '0002_assignment_accepted_at_assignment_backup_evaluator_and_more'),
        ('configuration', '0003_configurationchangerequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('state', models.CharField(choices=[('ready', 'Ready'), ('draft', 'Draft'), ('review', 'Review'), ('submitted', 'Submitted'), ('moderation', 'Moderation'), ('revaluation', 'Revaluation'), ('finalized', 'Finalized'), ('expired', 'Expired')], default='ready', max_length=16)),
                ('last_page', models.PositiveSmallIntegerField(default=1)),
                ('draft_checksum', models.CharField(blank=True, max_length=64)),
                ('draft_expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='workflow', to='allocation.assignment')),
                ('last_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_positions', to='configuration.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('requested_until', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=16)),
                ('requested_by_id', models.PositiveBigIntegerField()),
                ('decided_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extensions', to='workflow.evaluationworkflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('from_state', models.CharField(max_length=16)),
                ('to_state', models.CharField(max_length=16)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='workflow.evaluationworkflow')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('client_sequence', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('last_page', models.PositiveSmallIntegerField(default=1)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('last_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_positions', to='configuration.question')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='workflow.evaluationworkflow')),
            ],
            options={
                'ordering': ['-client_sequence'],
                'constraints': [models.UniqueConstraint(fields=('workflow', 'client_sequence'), name='unique_workflow_draft_sequence')],
            },
        ),
    ]
