# Generated by Django 5.2.6 on 2026-09-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remunerationstatement',
            name='calculated_by_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
