# Generated by Django 5.2.6 on 2026-09-08 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_assignment_accepted_at_assignment_backup_evaluator_and_more'),
        ('evaluators', '0003_alter_evaluator_status'),
        ('phase4', '0002_remunerationstatement_calculated_by_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureEvaluationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('access_session_id', models.UUIDField()),
                ('session_fingerprint', models.CharField(max_length=64)),
                ('device_fingerprint', models.CharField(max_length=64)),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('preflight', models.JSONField(default=dict)),
                ('device_inventory', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=16)),
                ('pause_reason', models.CharField(blank=True, max_length=80)),
                ('violation_count', models.PositiveSmallIntegerField(default=0)),
                ('consented_at', models.DateTimeField()),
                ('started_at', models.DateTimeField()),
                ('last_heartbeat_at', models.DateTimeField()),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secure_sessions', to='allocation.assignment')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secure_sessions', to='evaluators.evaluator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProctoringReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('cleared', 'Cleared'), ('escalated', 'Escalated')], default='pending', max_length=16)),
                ('decision_note', models.TextField(blank=True)),
                ('reviewer_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='phase4.presencesecurityevent')),
                ('secure_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='phase4.secureevaluationsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProctoringEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('sequence', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=80)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('captured_from', models.DateTimeField()),
                ('captured_to', models.DateTimeField()),
                ('retention_until', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending upload'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='phase4.presencesecurityevent')),
                ('secure_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='phase4.secureevaluationsession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('secure_session', 'sequence'), name='unique_proctoring_evidence_sequence')],
            },
        ),
    ]
