# Generated by Django 5.2.6 on 2026-09-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase4', '0003_secureevaluationsession_proctoringreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringevidence',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending upload'), ('verified', 'Verified'), ('failed', 'Failed'), ('expired', 'Expired and purged')], default='pending', max_length=16),
        ),
    ]
