# Generated by Django 5.2.6 on 2026-09-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_assignment_accepted_at_assignment_backup_evaluator_and_more'),
        ('custody', '0004_script_recognized_cover_sha256'),
        ('evaluators', '0006_evaluator_is_system_ai'),
        ('phase4', '0004_alter_proctoringevidence_status'),
        ('valuation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revaluationrequest',
            name='external_application_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='revaluationrequest',
            name='external_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='revaluationrequest',
            name='integration_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revaluation_requests', to='phase4.integrationendpoint'),
        ),
        migrations.AddField(
            model_name='revaluationrequest',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revaluationrequest',
            name='source_system',
            field=models.CharField(db_index=True, default='admiezo', max_length=50),
        ),
        migrations.AlterField(
            model_name='revaluationrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('assigned', 'Assigned'), ('evaluated', 'Evaluated'), ('decided', 'Decided'), ('closed', 'Closed'), ('rejected', 'Rejected')], db_index=True, default='requested', max_length=16),
        ),
        migrations.AddIndex(
            model_name='revaluationrequest',
            index=models.Index(fields=['tenant_id', 'status'], name='reval_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='revaluationrequest',
            index=models.Index(fields=['tenant_id', 'source_system', 'external_application_id'], name='reval_external_app_idx'),
        ),
        migrations.AddConstraint(
            model_name='revaluationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('external_application_id', ''), _negated=True), fields=('tenant_id', 'source_system', 'external_application_id'), name='unique_external_revaluation_application'),
        ),
    ]
