# Generated by Django 5.2.6 on 2026-09-07 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('receiving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('script_code', models.CharField(max_length=48, unique=True)),
                ('primary_barcode', models.CharField(max_length=64, unique=True)),
                ('supplement_barcodes', models.JSONField(blank=True, default=list)),
                ('page_count', models.PositiveSmallIntegerField(default=0)),
                ('state', models.CharField(choices=[('received', 'Received'), ('registered', 'Registered'), ('scanned', 'Scanned'), ('validated', 'Validated'), ('masked', 'Masked'), ('stored', 'Stored'), ('assigned', 'Assigned'), ('opened', 'Opened'), ('evaluating', 'Evaluation started'), ('submitted', 'Evaluation submitted'), ('review', 'Under review'), ('moderated', 'Moderated'), ('revaluated', 'Revaluated'), ('finalized', 'Finalized'), ('archived', 'Archived'), ('exception', 'Exception')], default='received', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scripts', to='receiving.packet')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scripts', to='configuration.paper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('from_state', models.CharField(max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=120)),
                ('actor_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='custody.script')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
