# Generated by Django 5.2.6 on 2026-09-07 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0001_initial'),
        ('receiving', '0002_dispatch_carrier_dispatch_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='bundle_barcode',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='script',
            name='centre_barcode',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='script',
            name='last_location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='BarcodeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('script', 'Script'), ('supplement', 'Supplement'), ('bundle', 'Bundle'), ('packet', 'Packet'), ('centre', 'Centre')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_by_id', models.PositiveBigIntegerField()),
                ('packet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_barcodes', to='receiving.packet')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='barcodes', to='custody.script')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BarcodeScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('purpose', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=120)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('result', models.CharField(max_length=24)),
                ('details', models.JSONField(default=dict)),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to='custody.script')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustodyTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('from_location', models.CharField(max_length=120)),
                ('to_location', models.CharField(max_length=120)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('authorized', 'Authorized'), ('in_transit', 'In transit'), ('received', 'Received'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('requested_by_id', models.PositiveBigIntegerField()),
                ('authorized_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('received_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='custody.script')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('expected_scripts', models.PositiveIntegerField()),
                ('observed_scripts', models.PositiveIntegerField()),
                ('missing_barcodes', models.JSONField(default=list)),
                ('excess_barcodes', models.JSONField(default=list)),
                ('mismatched_barcodes', models.JSONField(default=list)),
                ('duplicate_barcodes', models.JSONField(default=list)),
                ('status', models.CharField(max_length=20)),
                ('performed_by_id', models.PositiveBigIntegerField()),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='receiving.packet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
