# Generated by Django 5.2.6 on 2026-09-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0002_script_bundle_barcode_script_centre_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='removal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='script',
            name='removed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='removed_by_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
