# Generated by Django 5.2.6 on 2026-09-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0003_script_removal_reason_script_removed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='recognized_cover_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
