# Generated by Django 5.2.6 on 2026-09-08 03:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscrepancyCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('clarification', 'Clarification requested'), ('moderator', 'Moderator review'), ('chief_examiner', 'Chief examiner review'), ('third_requested', 'Third valuation requested'), ('resolved', 'Resolved'), ('approved', 'Approved')], default='open', max_length=24)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=8)),
                ('items', models.JSONField(default=list)),
                ('assigned_role', models.CharField(default='moderator', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscrepancyResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('method', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('rule_based', 'Rule based'), ('third_valuation', 'Third valuation'), ('override', 'Override')], max_length=20)),
                ('final_mark', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reason', models.TextField()),
                ('decided_by_id', models.PositiveBigIntegerField()),
                ('approved_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('calculation', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExaminerClarification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('valuation_round', models.PositiveSmallIntegerField()),
                ('requested_by_id', models.PositiveBigIntegerField()),
                ('request', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('responded_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
