# Generated by Django 5.2.6 on 2026-09-08 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discrepancy', '0001_initial'),
        ('valuation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discrepancycase',
            name='comparison',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancy_case', to='valuation.valuationcomparison'),
        ),
        migrations.AddField(
            model_name='discrepancyresolution',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolutions', to='discrepancy.discrepancycase'),
        ),
        migrations.AddField(
            model_name='examinerclarification',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clarifications', to='discrepancy.discrepancycase'),
        ),
    ]
