# Generated by Django 5.2.6 on 2026-09-08 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0003_configurationchangerequest_and_more'),
        ('custody', '0002_script_bundle_barcode_script_centre_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('reference', models.CharField(max_length=64)),
                ('requested_topology', models.CharField(choices=[('central', 'Central'), ('distributed', 'Distributed')], max_length=16)),
                ('duplex', models.BooleanField(default=True)),
                ('adf', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('assigned', 'Assigned'), ('scanning', 'Scanning'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('operator_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('expected_scripts', models.PositiveIntegerField(default=0)),
                ('completed_scripts', models.PositiveIntegerField(default=0)),
                ('failed_scripts', models.PositiveIntegerField(default=0)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_batches', to='configuration.paper')),
            ],
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed'), ('rescan', 'Re-scan required'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('expected_pages', models.PositiveSmallIntegerField(default=0)),
                ('scanned_pages', models.PositiveSmallIntegerField(default=0)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('source_manifest', models.JSONField(default=list)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='scanning.scanbatch')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_jobs', to='custody.script')),
            ],
        ),
        migrations.CreateModel(
            name='ScannerDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=160)),
                ('topology', models.CharField(choices=[('central', 'Central'), ('distributed', 'Distributed')], default='central', max_length=16)),
                ('capabilities', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('online', 'Online'), ('degraded', 'Degraded'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='offline', max_length=16)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pages_per_minute', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('pages_scanned_today', models.PositiveIntegerField(default=0)),
                ('failure_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('firmware_version', models.CharField(blank=True, max_length=80)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code'), name='unique_tenant_scanner_code')],
            },
        ),
        migrations.AddField(
            model_name='scanbatch',
            name='failover_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='failed_over_batches', to='scanning.scannerdevice'),
        ),
        migrations.AddField(
            model_name='scanbatch',
            name='scanner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='scanning.scannerdevice'),
        ),
        migrations.CreateModel(
            name='ScannerErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('recoverable', models.BooleanField(default=True)),
                ('telemetry', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='errors', to='scanning.scanbatch')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='errors', to='scanning.scanjob')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='errors', to='scanning.scannerdevice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScannerMaintenanceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('severity', models.CharField(default='medium', max_length=16)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('resolved_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_alerts', to='scanning.scannerdevice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='scanjob',
            constraint=models.UniqueConstraint(fields=('batch', 'script'), name='unique_batch_script_scan'),
        ),
        migrations.AddConstraint(
            model_name='scanbatch',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'reference'), name='unique_tenant_scan_batch'),
        ),
    ]
