# Generated by Django 5.2.6 on 2026-09-07 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('label', models.CharField(max_length=20)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'label'), name='unique_tenant_year')],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('term', models.CharField(max_length=60)),
                ('evaluation_starts_at', models.DateTimeField()),
                ('evaluation_ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approval', 'Awaiting approval'), ('ready', 'Ready'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='configuration.academicyear')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=160)),
                ('regulation', models.CharField(max_length=80)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code'), name='unique_tenant_programme')],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=180)),
                ('semester', models.PositiveSmallIntegerField()),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='configuration.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pass_marks', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valuation_rounds', models.PositiveSmallIntegerField(default=1)),
                ('discrepancy_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('moderation_required', models.BooleanField(default=False)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('approved', 'Approved'), ('frozen', 'Frozen')], default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('approved_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='configuration.examsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='configuration.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('number', models.CharField(max_length=16)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=7)),
                ('required', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='configuration.paper')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('paper', 'number'), name='unique_paper_question')],
            },
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'code'), name='unique_tenant_subject'),
        ),
        migrations.AddConstraint(
            model_name='paper',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'session', 'code'), name='unique_session_paper'),
        ),
    ]
