# Generated by Django 5.2.6 on 2026-09-07 13:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='effective_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConfigurationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.UUIDField()),
                ('version', models.PositiveIntegerField()),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('approve', 'Approve'), ('freeze', 'Freeze'), ('rollback', 'Rollback'), ('emergency', 'Emergency change')], max_length=16)),
                ('snapshot', models.JSONField()),
                ('reason', models.TextField(blank=True)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'aggregate_type', 'aggregate_id', 'version'), name='unique_config_revision')],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCentre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=180)),
                ('address', models.TextField(blank=True)),
                ('network_cidrs', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code'), name='unique_tenant_centre')],
            },
        ),
        migrations.CreateModel(
            name='EvaluationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=140)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('evaluation_centre_ids', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='configuration.examsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code'), name='unique_tenant_regulation')],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('stage', models.PositiveSmallIntegerField()),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('note', models.TextField(blank=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='configuration.paper')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('paper', 'stage', 'actor_id'), name='unique_paper_approval_actor')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=180)),
                ('duration_terms', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='configuration.programme')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='configuration.regulation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'code'), name='unique_tenant_course')],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=80)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='configuration.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'sequence'), name='unique_year_term_sequence')],
            },
        ),
    ]
