# Generated by Django 5.2.6 on 2026-09-07 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_paper_effective_from_configurationrevision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(choices=[('emergency_update', 'Emergency update'), ('rollback', 'Rollback')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('base_version', models.PositiveIntegerField()),
                ('target_revision_version', models.PositiveIntegerField(blank=True, null=True)),
                ('proposed_changes', models.JSONField(blank=True, default=dict)),
                ('impact', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('submitted_by_id', models.PositiveBigIntegerField()),
                ('required_approvals', models.PositiveSmallIntegerField(default=2)),
                ('version', models.PositiveIntegerField(default=1)),
                ('applied_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='configuration.paper')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationChangeApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('actor_id', models.PositiveBigIntegerField()),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='configuration.configurationchangerequest')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('change_request', 'actor_id'), name='unique_config_change_approver')],
            },
        ),
    ]
