# Generated by Django 5.2.6 on 2026-09-16 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_configurationchangerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='configuration.course'),
        ),
        migrations.AddField(
            model_name='subject',
            name='related_subject_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subject',
            name='session_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
