# Generated by Django 5.2.6 on 2026-09-17 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_link_legacy_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarOverlapException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('entity', models.CharField(choices=[('academic_year', 'Academic year'), ('term', 'Term')], max_length=16)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('used', 'Used')], default='pending', max_length=12)),
                ('requested_by_id', models.PositiveBigIntegerField()),
                ('decided_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuration.academicyear')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
