# Generated by Django 5.2.6 on 2026-09-08 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repository', '0003_remove_uploadintent_one_completed_upload_per_script_kind_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('kind', models.CharField(max_length=40)),
                ('severity', models.CharField(default='critical', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('details', models.JSONField(default=dict)),
                ('acknowledged_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('resolved_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrityEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('evidence_type', models.CharField(max_length=40)),
                ('storage_key', models.CharField(blank=True, max_length=320)),
                ('snapshot', models.JSONField(default=dict)),
                ('sha256', models.CharField(max_length=64)),
                ('preserved_at', models.DateTimeField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='integrity.integrityalert')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrityManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('file_sha256', models.CharField(max_length=64)),
                ('metadata_sha256', models.CharField(max_length=64)),
                ('custody_sha256', models.CharField(max_length=64)),
                ('version_sha256', models.CharField(max_length=64)),
                ('signature', models.TextField()),
                ('public_key', models.TextField()),
                ('signed_at', models.DateTimeField()),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(default='pending', max_length=16)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='integrity_manifest', to='repository.scriptasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('missing', 'Missing')], max_length=16)),
                ('observed', models.JSONField(default=dict)),
                ('checked_by', models.CharField(default='scheduled-verifier', max_length=64)),
                ('checked_at', models.DateTimeField()),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='integrity.integritymanifest')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.AddField(
            model_name='integrityalert',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='integrity.integritymanifest'),
        ),
    ]
