# Generated by Django 5.2.6 on 2026-09-08 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custody', '0002_script_bundle_barcode_script_centre_barcode_and_more'),
        ('marking', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevealAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('from_round', models.PositiveSmallIntegerField()),
                ('to_round', models.PositiveSmallIntegerField()),
                ('purpose', models.TextField()),
                ('requested_by_id', models.PositiveBigIntegerField()),
                ('approved_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reveal_authorizations', to='custody.script')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValuationComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('question_differences', models.JSONField(default=dict)),
                ('total_difference', models.DecimalField(decimal_places=2, max_digits=8)),
                ('percentage_difference', models.DecimalField(decimal_places=3, max_digits=8)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('within_threshold', 'Within threshold'), ('discrepancy', 'Discrepancy'), ('third_required', 'Third valuation required'), ('reconciled', 'Reconciled')], max_length=20)),
                ('requires_third_valuation', models.BooleanField(default=False)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuation_comparisons', to='custody.script')),
            ],
        ),
        migrations.CreateModel(
            name='FinalMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('rule', models.CharField(choices=[('best', 'Best mark'), ('average', 'Average mark'), ('rule_based', 'Rule based'), ('approved', 'Approved final mark')], max_length=16)),
                ('mark', models.DecimalField(decimal_places=2, max_digits=8)),
                ('calculation', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('locked', 'Locked')], default='proposed', max_length=16)),
                ('proposed_by_id', models.PositiveBigIntegerField()),
                ('approved_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('locked_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='final_mark', to='custody.script')),
                ('comparison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_marks', to='valuation.valuationcomparison')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValuationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('valuation_round', models.PositiveSmallIntegerField()),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=8)),
                ('question_snapshot', models.JSONField(default=dict)),
                ('checksum', models.CharField(max_length=64)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='valuation_result', to='marking.evaluation')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuation_results', to='custody.script')),
            ],
        ),
        migrations.AddField(
            model_name='valuationcomparison',
            name='first_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons_as_first', to='valuation.valuationresult'),
        ),
        migrations.AddField(
            model_name='valuationcomparison',
            name='second_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons_as_second', to='valuation.valuationresult'),
        ),
        migrations.AddField(
            model_name='valuationcomparison',
            name='third_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comparisons_as_third', to='valuation.valuationresult'),
        ),
        migrations.AddConstraint(
            model_name='valuationresult',
            constraint=models.UniqueConstraint(fields=('script', 'valuation_round'), name='unique_script_valuation_result'),
        ),
        migrations.AddConstraint(
            model_name='valuationcomparison',
            constraint=models.UniqueConstraint(fields=('script', 'first_result', 'second_result'), name='unique_valuation_comparison'),
        ),
    ]
