import type { LanguageCode } from "@/i18n/client";

type CoverageLocalizations = Record<LanguageCode, Record<string, string>>;

/** Final coverage for API-composed labels and values that can appear after initial render. */
export const coverageLocalizations: CoverageLocalizations = {
  en: {},
  hi: {
    Unpublished: "अप्रकाशित", "Unpublished audit events": "अप्रकाशित लेखापरीक्षा घटनाएँ", Configuration: "विन्यास", Evaluators: "मूल्यांकनकर्ता", Custody: "अभिरक्षा", Discrepancy: "विसंगति", Register: "अभिलेख", register: "अभिलेख", Metrics: "मापदंड", METRICS: "मापदंड", ID: "पहचान", IDs: "पहचानें", "Session IDs": "सत्र पहचानें", "Related Event IDs": "संबंधित घटना पहचानें", Units: "इकाइयाँ", "Gross Amount": "सकल राशि", Deductions: "कटौतियाँ", "Net Amount": "शुद्ध राशि", Master: "मुख्य प्रति", Thumbnail: "लघुचित्र", Expired: "समाप्त", Identities: "पहचानें", identities: "पहचानें", "identities for your account": "आपके खाते की पहचानें", Demonstrates: "प्रदर्शित करता है", concepts: "अवधारणाएँ", Concepts: "अवधारणाएँ", reasoning: "तर्क", Reasoning: "तर्क", for: "के लिए", Advanced: "उन्नत", advanced: "उन्नत", "Asia/Kolkata": "एशिया/कोलकाता", ADF: "स्वचालित दस्तावेज़ फीडर", Duplex: "दोतरफ़ा", TOTP: "समय-आधारित एकल पासवर्ड",
  },
  kn: {
    Unpublished: "ಅಪ್ರಕಟಿತ", "Unpublished audit events": "ಅಪ್ರಕಟಿತ ಲೆಕ್ಕಪರಿಶೋಧನಾ ಘಟನೆಗಳು", Configuration: "ಸಂರಚನೆ", Evaluators: "ಮೌಲ್ಯಮಾಪಕರು", Custody: "ಅಭಿರಕ್ಷೆ", Discrepancy: "ವ್ಯತ್ಯಾಸ", Register: "ದಾಖಲೆ", register: "ದಾಖಲೆ", Metrics: "ಮಾಪಕಗಳು", METRICS: "ಮಾಪಕಗಳು", ID: "ಗುರುತು", IDs: "ಗುರುತುಗಳು", "Session IDs": "ಸೆಷನ್ ಗುರುತುಗಳು", "Related Event IDs": "ಸಂಬಂಧಿತ ಘಟನೆ ಗುರುತುಗಳು", Units: "ಘಟಕಗಳು", "Gross Amount": "ಒಟ್ಟು ಮೊತ್ತ", Deductions: "ಕಡಿತಗಳು", "Net Amount": "ನಿವ್ವಳ ಮೊತ್ತ", Master: "ಮೂಲಪ್ರತಿ", Thumbnail: "ಕಿರುಚಿತ್ರ", Expired: "ಅವಧಿ ಮುಗಿದಿದೆ", Identities: "ಗುರುತುಗಳು", identities: "ಗುರುತುಗಳು", "identities for your account": "ನಿಮ್ಮ ಖಾತೆಯ ಗುರುತುಗಳು", Demonstrates: "ತೋರಿಸುತ್ತದೆ", concepts: "ಪರಿಕಲ್ಪನೆಗಳು", Concepts: "ಪರಿಕಲ್ಪನೆಗಳು", reasoning: "ತಾರ್ಕಿಕತೆ", Reasoning: "ತಾರ್ಕಿಕತೆ", for: "ಗಾಗಿ", Advanced: "ಉನ್ನತ", advanced: "ಉನ್ನತ", "Asia/Kolkata": "ಏಷ್ಯಾ/ಕೋಲ್ಕತಾ", ADF: "ಸ್ವಯಂಚಾಲಿತ ದಾಖಲೆ ಪೂರಕ", Duplex: "ಎರಡುಮುಖ", TOTP: "ಸಮಯಾಧಾರಿತ ಏಕಬಳಕೆ ಗುಪ್ತಪದ",
  },
  ta: {
    Unpublished: "வெளியிடப்படாத", "Unpublished audit events": "வெளியிடப்படாத தணிக்கை நிகழ்வுகள்", Configuration: "அமைப்பு", Evaluators: "மதிப்பீட்டாளர்கள்", Custody: "பாதுகாப்புப் பொறுப்பு", Discrepancy: "முரண்பாடு", Register: "பதிவேடு", register: "பதிவேடு", Metrics: "அளவீடுகள்", METRICS: "அளவீடுகள்", ID: "அடையாளம்", IDs: "அடையாளங்கள்", "Session IDs": "அமர்வு அடையாளங்கள்", "Related Event IDs": "தொடர்புடைய நிகழ்வு அடையாளங்கள்", Units: "அலகுகள்", "Gross Amount": "மொத்தத் தொகை", Deductions: "கழிவுகள்", "Net Amount": "நிகரத் தொகை", Master: "முதன்மைப் பிரதி", Thumbnail: "சிறுபடம்", Expired: "காலாவதியானது", Identities: "அடையாளங்கள்", identities: "அடையாளங்கள்", "identities for your account": "உங்கள் கணக்கிற்கான அடையாளங்கள்", Demonstrates: "விளக்குகிறது", concepts: "கருத்துக்கள்", Concepts: "கருத்துக்கள்", reasoning: "பகுத்தறிவு", Reasoning: "பகுத்தறிவு", for: "க்கான", Advanced: "மேம்பட்ட", advanced: "மேம்பட்ட", "Asia/Kolkata": "ஆசியா/கொல்கத்தா", ADF: "தானியங்கி ஆவண ஊட்டி", Duplex: "இருபக்கம்", TOTP: "நேர அடிப்படையிலான ஒருமுறை கடவுச்சொல்",
  },
  te: {
    Unpublished: "ప్రచురించని", "Unpublished audit events": "ప్రచురించని ఆడిట్ సంఘటనలు", Configuration: "ఆకృతీకరణ", Evaluators: "మూల్యాంకనకర్తలు", Custody: "అభిరక్షణ", Discrepancy: "వ్యత్యాసం", Register: "నమోదు", register: "నమోదు", Metrics: "కొలమానాలు", METRICS: "కొలమానాలు", ID: "గుర్తింపు", IDs: "గుర్తింపులు", "Session IDs": "సెషన్ గుర్తింపులు", "Related Event IDs": "సంబంధిత సంఘటన గుర్తింపులు", Units: "యూనిట్లు", "Gross Amount": "స్థూల మొత్తం", Deductions: "తగ్గింపులు", "Net Amount": "నికర మొత్తం", Master: "ప్రధాన ప్రతి", Thumbnail: "చిన్న చిత్రం", Expired: "గడువు ముగిసింది", Identities: "గుర్తింపులు", identities: "గుర్తింపులు", "identities for your account": "మీ ఖాతా గుర్తింపులు", Demonstrates: "ప్రదర్శిస్తుంది", concepts: "భావనలు", Concepts: "భావనలు", reasoning: "తార్కికత", Reasoning: "తార్కికత", for: "కోసం", Advanced: "ఉన్నత", advanced: "ఉన్నత", "Asia/Kolkata": "ఆసియా/కోల్‌కతా", ADF: "స్వయంచాలిత పత్ర సరఫరా", Duplex: "రెండువైపుల", TOTP: "సమయ ఆధారిత ఒకసారి సంకేతపదం",
  },
  mr: {
    Unpublished: "अप्रकाशित", "Unpublished audit events": "अप्रकाशित लेखापरीक्षण घटना", Configuration: "संरचना", Evaluators: "मूल्यमापक", Custody: "अभिरक्षा", Discrepancy: "विसंगती", Register: "नोंदवही", register: "नोंदवही", Metrics: "मापदंड", METRICS: "मापदंड", ID: "ओळख", IDs: "ओळखी", "Session IDs": "सत्र ओळखी", "Related Event IDs": "संबंधित घटना ओळखी", Units: "एकके", "Gross Amount": "एकूण रक्कम", Deductions: "वजावटी", "Net Amount": "निव्वळ रक्कम", Master: "मूळ प्रत", Thumbnail: "लघुप्रतिमा", Expired: "कालबाह्य", Identities: "ओळखी", identities: "ओळखी", "identities for your account": "तुमच्या खात्याच्या ओळखी", Demonstrates: "दर्शवते", concepts: "संकल्पना", Concepts: "संकल्पना", reasoning: "तर्क", Reasoning: "तर्क", for: "साठी", Advanced: "प्रगत", advanced: "प्रगत", "Asia/Kolkata": "आशिया/कोलकाता", ADF: "स्वयंचलित दस्तऐवज पुरवठा", Duplex: "दुतर्फा", TOTP: "कालाधारित एकवेळ संकेतशब्द",
  },
};
