import type { LanguageCode } from "@/i18n/client";

type DomainLocalizations = Record<LanguageCode, Record<string, string>>;

/** API-generated security, audit, access, and marking labels. */
export const domainLocalizations: DomainLocalizations = {
  en: {},
  hi: {
    Login: "लॉगिन", Success: "सफल", Challenged: "चुनौती दी गई", Performed: "की गई", "Auth Login Succeeded": "प्रमाणीकरण लॉगिन सफल", "Auth Session Revoked": "प्रमाणीकरण सत्र रद्द किया गया", "Action Performed": "की गई कार्रवाई", Date: "दिनांक", Details: "विवरण", Reason: "कारण", Score: "अंक", True: "सही", False: "गलत", "User Logout": "उपयोगकर्ता लॉगआउट",
    "University Admin": "विश्वविद्यालय प्रशासक", "University Administrator": "विश्वविद्यालय प्रशासक", "University Defaults": "विश्वविद्यालय डिफ़ॉल्ट", Admin: "प्रशासक", Evaluator: "मूल्यांकनकर्ता", "Exam Controller": "परीक्षा नियंत्रक", Auditor: "लेखा परीक्षक", "Receiving Officer": "प्राप्ति अधिकारी",
    "Authenticator Clock": "प्रमाणक घड़ी", "Encryption At Rest": "संग्रहित डेटा कूटलेखन", "Tls Enforced": "टीएलएस लागू", "Database Protection": "डेटाबेस सुरक्षा", "File Protection": "फ़ाइल सुरक्षा", "Key Management": "कुंजी प्रबंधन", "Secrets Management": "गोपनीयता प्रबंधन", "Secure Cookies": "सुरक्षित कुकीज़", Rbac: "भूमिका-आधारित पहुँच नियंत्रण", "Least Privilege": "न्यूनतम विशेषाधिकार", "Zero Trust Access": "शून्य-विश्वास पहुँच", "Identity Store Isolated": "पहचान भंडार पृथक", "Script Store Isolated": "उत्तरपुस्तिका भंडार पृथक", "Identity Service Authorization": "पहचान सेवा प्राधिकरण", "Controlled Identity Resolution": "नियंत्रित पहचान समाधान", "Waf Configured": "वेब सुरक्षा परत कॉन्फ़िगर", "Ddos Protection": "डीडीओएस सुरक्षा", "Intrusion Detection": "घुसपैठ पहचान", "Security Monitoring": "सुरक्षा निगरानी", "Siem Configured": "एसआईईएम कॉन्फ़िगर", "Vulnerability Monitoring": "भेद्यता निगरानी", "Security Alerts": "सुरक्षा चेतावनियाँ", "Dlp Enabled": "डेटा हानि रोकथाम सक्षम", Synchronized: "समकालित", Configured: "कॉन्फ़िगर किया गया", "Awaiting Deployment Configuration": "परिनियोजन कॉन्फ़िगरेशन की प्रतीक्षा",
    "standard marking scheme": "मानक अंकन योजना", standard: "मानक", marking: "अंकन", scheme: "योजना", "Award marks against the published criterion evidence": "प्रकाशित मानदंड साक्ष्य के अनुसार अंक दें", "Record zero-mark and unanswered outcomes explicitly": "शून्य-अंक और अनुत्तरित परिणाम स्पष्ट रूप से दर्ज करें",
  },
  kn: {
    Login: "ಲಾಗಿನ್", Success: "ಯಶಸ್ವಿ", Challenged: "ಸವಾಲು ಮಾಡಲಾಗಿದೆ", Performed: "ನಿರ್ವಹಿಸಲಾಗಿದೆ", "Auth Login Succeeded": "ದೃಢೀಕರಣ ಲಾಗಿನ್ ಯಶಸ್ವಿಯಾಗಿದೆ", "Auth Session Revoked": "ದೃಢೀಕರಣ ಸೆಷನ್ ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ", "Action Performed": "ನಿರ್ವಹಿಸಿದ ಕ್ರಿಯೆ", Date: "ದಿನಾಂಕ", Details: "ವಿವರಗಳು", Reason: "ಕಾರಣ", Score: "ಅಂಕ", True: "ಸರಿ", False: "ತಪ್ಪು", "User Logout": "ಬಳಕೆದಾರ ಲಾಗ್‌ಔಟ್",
    "University Admin": "ವಿಶ್ವವಿದ್ಯಾಲಯ ನಿರ್ವಾಹಕ", "University Administrator": "ವಿಶ್ವವಿದ್ಯಾಲಯ ನಿರ್ವಾಹಕ", "University Defaults": "ವಿಶ್ವವಿದ್ಯಾಲಯ ಪೂರ್ವನಿಯೋಜಿತಗಳು", Admin: "ನಿರ್ವಾಹಕ", Evaluator: "ಮೌಲ್ಯಮಾಪಕ", "Exam Controller": "ಪರೀಕ್ಷಾ ನಿಯಂತ್ರಕ", Auditor: "ಲೆಕ್ಕಪರಿಶೋಧಕ", "Receiving Officer": "ಸ್ವೀಕೃತಿ ಅಧಿಕಾರಿ",
    "Authenticator Clock": "ದೃಢೀಕರಣ ಗಡಿಯಾರ", "Encryption At Rest": "ಸಂಗ್ರಹಿತ ದತ್ತಾಂಶ ಗೂಢಲಿಪೀಕರಣ", "Tls Enforced": "ಟಿಎಲ್‌ಎಸ್ ಜಾರಿಯಲ್ಲಿದೆ", "Database Protection": "ದತ್ತಸಂಚಯ ರಕ್ಷಣೆ", "File Protection": "ಕಡತ ರಕ್ಷಣೆ", "Key Management": "ಕೀಲಿ ನಿರ್ವಹಣೆ", "Secrets Management": "ರಹಸ್ಯ ನಿರ್ವಹಣೆ", "Secure Cookies": "ಸುರಕ್ಷಿತ ಕುಕಿಗಳು", Rbac: "ಪಾತ್ರಾಧಾರಿತ ಪ್ರವೇಶ ನಿಯಂತ್ರಣ", "Least Privilege": "ಕನಿಷ್ಠ ಸವಲತ್ತು", "Zero Trust Access": "ಶೂನ್ಯ-ವಿಶ್ವಾಸ ಪ್ರವೇಶ", "Identity Store Isolated": "ಗುರುತು ಭಂಡಾರ ಪ್ರತ್ಯೇಕ", "Script Store Isolated": "ಉತ್ತರಪತ್ರಿಕೆ ಭಂಡಾರ ಪ್ರತ್ಯೇಕ", "Identity Service Authorization": "ಗುರುತು ಸೇವೆ ಅಧಿಕೃತತೆ", "Controlled Identity Resolution": "ನಿಯಂತ್ರಿತ ಗುರುತು ಪರಿಹಾರ", "Waf Configured": "ವೆಬ್ ಭದ್ರತಾ ಪದರ ಸಂರಚಿತ", "Ddos Protection": "ಡಿಡಿಒಎಸ್ ರಕ್ಷಣೆ", "Intrusion Detection": "ನುಸುಳುವಿಕೆ ಪತ್ತೆ", "Security Monitoring": "ಭದ್ರತಾ ಮೇಲ್ವಿಚಾರಣೆ", "Siem Configured": "ಎಸ್‌ಐಇಎಂ ಸಂರಚಿತ", "Vulnerability Monitoring": "ದುರ್ಬಲತೆ ಮೇಲ್ವಿಚಾರಣೆ", "Security Alerts": "ಭದ್ರತಾ ಎಚ್ಚರಿಕೆಗಳು", "Dlp Enabled": "ದತ್ತಾಂಶ ನಷ್ಟ ತಡೆ ಸಕ್ರಿಯ", Synchronized: "ಸಮನ್ವಯಗೊಂಡಿದೆ", Configured: "ಸಂರಚಿತವಾಗಿದೆ", "Awaiting Deployment Configuration": "ನಿಯೋಜನೆ ಸಂರಚನೆಗಾಗಿ ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ",
    "standard marking scheme": "ಪ್ರಮಾಣಿತ ಅಂಕನ ಯೋಜನೆ", standard: "ಪ್ರಮಾಣಿತ", marking: "ಅಂಕನ", scheme: "ಯೋಜನೆ", "Award marks against the published criterion evidence": "ಪ್ರಕಟಿತ ಮಾನದಂಡದ ಸಾಕ್ಷ್ಯದ ಆಧಾರದಲ್ಲಿ ಅಂಕಗಳನ್ನು ನೀಡಿ", "Record zero-mark and unanswered outcomes explicitly": "ಶೂನ್ಯ ಅಂಕ ಮತ್ತು ಉತ್ತರಿಸದ ಫಲಿತಾಂಶಗಳನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ದಾಖಲಿಸಿ",
  },
  ta: {
    Login: "உள்நுழைவு", Success: "வெற்றி", Challenged: "சவால் விடப்பட்டது", Performed: "செய்யப்பட்டது", "Auth Login Succeeded": "அங்கீகார உள்நுழைவு வெற்றி", "Auth Session Revoked": "அங்கீகார அமர்வு திரும்பப் பெறப்பட்டது", "Action Performed": "செய்யப்பட்ட நடவடிக்கை", Date: "தேதி", Details: "விவரங்கள்", Reason: "காரணம்", Score: "மதிப்பெண்", True: "உண்மை", False: "தவறு", "User Logout": "பயனர் வெளியேற்றம்",
    "University Admin": "பல்கலைக்கழக நிர்வாகி", "University Administrator": "பல்கலைக்கழக நிர்வாகி", "University Defaults": "பல்கலைக்கழக இயல்புநிலைகள்", Admin: "நிர்வாகி", Evaluator: "மதிப்பீட்டாளர்", "Exam Controller": "தேர்வுக் கட்டுப்பாட்டாளர்", Auditor: "தணிக்கையாளர்", "Receiving Officer": "பெறுதல் அலுவலர்",
    "Authenticator Clock": "அங்கீகாரக் கடிகாரம்", "Encryption At Rest": "சேமித்த தரவு குறியாக்கம்", "Tls Enforced": "டிஎல்எஸ் அமலில்", "Database Protection": "தரவுத்தள பாதுகாப்பு", "File Protection": "கோப்பு பாதுகாப்பு", "Key Management": "விசை மேலாண்மை", "Secrets Management": "ரகசிய மேலாண்மை", "Secure Cookies": "பாதுகாப்பான குக்கிகள்", Rbac: "பங்கு அடிப்படையிலான அணுகல் கட்டுப்பாடு", "Least Privilege": "குறைந்தபட்ச சலுகை", "Zero Trust Access": "பூஜ்ய நம்பிக்கை அணுகல்", "Identity Store Isolated": "அடையாளக் களஞ்சியம் தனிமைப்படுத்தப்பட்டது", "Script Store Isolated": "விடைத்தாள் களஞ்சியம் தனிமைப்படுத்தப்பட்டது", "Identity Service Authorization": "அடையாளச் சேவை அங்கீகாரம்", "Controlled Identity Resolution": "கட்டுப்படுத்தப்பட்ட அடையாளத் தீர்வு", "Waf Configured": "இணையப் பாதுகாப்பு அடுக்கு அமைக்கப்பட்டது", "Ddos Protection": "டிடிஓஎஸ் பாதுகாப்பு", "Intrusion Detection": "ஊடுருவல் கண்டறிதல்", "Security Monitoring": "பாதுகாப்புக் கண்காணிப்பு", "Siem Configured": "எஸ்ஐஇஎம் அமைக்கப்பட்டது", "Vulnerability Monitoring": "பாதிப்பு கண்காணிப்பு", "Security Alerts": "பாதுகாப்பு எச்சரிக்கைகள்", "Dlp Enabled": "தரவு இழப்பு தடுப்பு இயக்கப்பட்டது", Synchronized: "ஒத்திசைக்கப்பட்டது", Configured: "அமைக்கப்பட்டது", "Awaiting Deployment Configuration": "நிறுவல் அமைப்பிற்காகக் காத்திருக்கிறது",
    "standard marking scheme": "நிலையான மதிப்பீட்டுத் திட்டம்", standard: "நிலையான", marking: "மதிப்பீடு", scheme: "திட்டம்", "Award marks against the published criterion evidence": "வெளியிடப்பட்ட அளவுகோல் சான்றின் அடிப்படையில் மதிப்பெண்கள் வழங்கவும்", "Record zero-mark and unanswered outcomes explicitly": "பூஜ்ய மதிப்பெண் மற்றும் பதிலளிக்காத முடிவுகளைத் தெளிவாகப் பதிவு செய்யவும்",
  },
  te: {
    Login: "లాగిన్", Success: "విజయం", Challenged: "సవాలు చేయబడింది", Performed: "చేయబడింది", "Auth Login Succeeded": "ధృవీకరణ లాగిన్ విజయవంతమైంది", "Auth Session Revoked": "ధృవీకరణ సెషన్ రద్దు చేయబడింది", "Action Performed": "చేసిన చర్య", Date: "తేదీ", Details: "వివరాలు", Reason: "కారణం", Score: "స్కోరు", True: "నిజం", False: "తప్పు", "User Logout": "వినియోగదారు లాగ్‌అవుట్",
    "University Admin": "విశ్వవిద్యాలయ నిర్వాహకుడు", "University Administrator": "విశ్వవిద్యాలయ నిర్వాహకుడు", "University Defaults": "విశ్వవిద్యాలయ డిఫాల్ట్‌లు", Admin: "నిర్వాహకుడు", Evaluator: "మూల్యాంకనకర్త", "Exam Controller": "పరీక్ష నియంత్రకుడు", Auditor: "ఆడిటర్", "Receiving Officer": "స్వీకరణ అధికారి",
    "Authenticator Clock": "ధృవీకరణ గడియారం", "Encryption At Rest": "నిల్వ దత్తాంశ గుప్తీకరణ", "Tls Enforced": "టీఎల్ఎస్ అమలులో", "Database Protection": "డేటాబేస్ రక్షణ", "File Protection": "ఫైల్ రక్షణ", "Key Management": "కీ నిర్వహణ", "Secrets Management": "రహస్యాల నిర్వహణ", "Secure Cookies": "సురక్షిత కుకీలు", Rbac: "పాత్ర ఆధారిత ప్రాప్యత నియంత్రణ", "Least Privilege": "కనిష్ట ప్రత్యేకాధికారం", "Zero Trust Access": "శూన్య నమ్మకం ప్రాప్యత", "Identity Store Isolated": "గుర్తింపు భాండాగారం వేరు చేయబడింది", "Script Store Isolated": "జవాబు పత్ర భాండాగారం వేరు చేయబడింది", "Identity Service Authorization": "గుర్తింపు సేవ అధికారీకరణ", "Controlled Identity Resolution": "నియంత్రిత గుర్తింపు పరిష్కారం", "Waf Configured": "వెబ్ భద్రతా పొర అమర్చబడింది", "Ddos Protection": "డీడీఓఎస్ రక్షణ", "Intrusion Detection": "చొరబాటు గుర్తింపు", "Security Monitoring": "భద్రతా పర్యవేక్షణ", "Siem Configured": "ఎస్ఐఈఎం అమర్చబడింది", "Vulnerability Monitoring": "దుర్బలత పర్యవేక్షణ", "Security Alerts": "భద్రతా హెచ్చరికలు", "Dlp Enabled": "డేటా నష్టం నివారణ ప్రారంభించబడింది", Synchronized: "సమన్వయించబడింది", Configured: "అమర్చబడింది", "Awaiting Deployment Configuration": "అమలు ఆకృతీకరణ కోసం వేచి ఉంది",
    "standard marking scheme": "ప్రామాణిక మార్కింగ్ పథకం", standard: "ప్రామాణిక", marking: "మార్కింగ్", scheme: "పథకం", "Award marks against the published criterion evidence": "ప్రచురించిన ప్రమాణ సాక్ష్యానికి అనుగుణంగా మార్కులు ఇవ్వండి", "Record zero-mark and unanswered outcomes explicitly": "సున్నా మార్కులు మరియు సమాధానం లేని ఫలితాలను స్పష్టంగా నమోదు చేయండి",
  },
  mr: {
    Login: "लॉगिन", Success: "यशस्वी", Challenged: "आव्हान दिले", Performed: "केलेली", "Auth Login Succeeded": "प्रमाणीकरण लॉगिन यशस्वी", "Auth Session Revoked": "प्रमाणीकरण सत्र रद्द केले", "Action Performed": "केलेली क्रिया", Date: "दिनांक", Details: "तपशील", Reason: "कारण", Score: "गुण", True: "बरोबर", False: "चूक", "User Logout": "वापरकर्ता लॉगआउट",
    "University Admin": "विद्यापीठ प्रशासक", "University Administrator": "विद्यापीठ प्रशासक", "University Defaults": "विद्यापीठ पूर्वनिर्धारित", Admin: "प्रशासक", Evaluator: "मूल्यमापक", "Exam Controller": "परीक्षा नियंत्रक", Auditor: "लेखापरीक्षक", "Receiving Officer": "स्वीकृती अधिकारी",
    "Authenticator Clock": "प्रमाणक घड्याळ", "Encryption At Rest": "साठवलेल्या डेटाचे कूटलेखन", "Tls Enforced": "टीएलएस लागू", "Database Protection": "डेटाबेस संरक्षण", "File Protection": "फाइल संरक्षण", "Key Management": "किल्ली व्यवस्थापन", "Secrets Management": "गुपित व्यवस्थापन", "Secure Cookies": "सुरक्षित कुकीज", Rbac: "भूमिका-आधारित प्रवेश नियंत्रण", "Least Privilege": "किमान विशेषाधिकार", "Zero Trust Access": "शून्य-विश्वास प्रवेश", "Identity Store Isolated": "ओळख भांडार विलग", "Script Store Isolated": "उत्तरपत्रिका भांडार विलग", "Identity Service Authorization": "ओळख सेवा प्राधिकरण", "Controlled Identity Resolution": "नियंत्रित ओळख निराकरण", "Waf Configured": "वेब सुरक्षा स्तर संरचित", "Ddos Protection": "डीडीओएस संरक्षण", "Intrusion Detection": "घुसखोरी शोध", "Security Monitoring": "सुरक्षा निरीक्षण", "Siem Configured": "एसआयईएम संरचित", "Vulnerability Monitoring": "असुरक्षा निरीक्षण", "Security Alerts": "सुरक्षा सूचना", "Dlp Enabled": "डेटा गळती प्रतिबंध सक्षम", Synchronized: "समक्रमित", Configured: "संरचित", "Awaiting Deployment Configuration": "उपयोजन संरचनेची प्रतीक्षा",
    "standard marking scheme": "मानक गुणांकन योजना", standard: "मानक", marking: "गुणांकन", scheme: "योजना", "Award marks against the published criterion evidence": "प्रकाशित निकष पुराव्यानुसार गुण द्या", "Record zero-mark and unanswered outcomes explicitly": "शून्य गुण आणि अनुत्तरित निकाल स्पष्टपणे नोंदवा",
  },
};

const domainExtras: DomainLocalizations = {
  en: {},
  hi: { "Awaiting deployment configuration": "परिनियोजन कॉन्फ़िगरेशन की प्रतीक्षा", Drift: "अंतर", drift: "अंतर", Seconds: "सेकंड", seconds: "सेकंड", s: "से", Mfa: "बहु-कारक प्रमाणीकरण", Risk: "जोखिम", User: "उपयोगकर्ता", Logout: "लॉगआउट" },
  kn: { "Awaiting deployment configuration": "ನಿಯೋಜನೆ ಸಂರಚನೆಗಾಗಿ ನಿರೀಕ್ಷಿಸಲಾಗುತ್ತಿದೆ", Drift: "ವ್ಯತ್ಯಾಸ", drift: "ವ್ಯತ್ಯಾಸ", Seconds: "ಸೆಕೆಂಡುಗಳು", seconds: "ಸೆಕೆಂಡುಗಳು", s: "ಸೆ", Mfa: "ಬಹು-ಅಂಶ ದೃಢೀಕರಣ", Risk: "ಅಪಾಯ", User: "ಬಳಕೆದಾರ", Logout: "ಲಾಗ್‌ಔಟ್" },
  ta: { "Awaiting deployment configuration": "நிறுவல் அமைப்பிற்காகக் காத்திருக்கிறது", Drift: "விலகல்", drift: "விலகல்", Seconds: "வினாடிகள்", seconds: "வினாடிகள்", s: "வி", Mfa: "பல காரணி அங்கீகாரம்", Risk: "ஆபத்து", User: "பயனர்", Logout: "வெளியேற்றம்" },
  te: { "Awaiting deployment configuration": "అమలు ఆకృతీకరణ కోసం వేచి ఉంది", Drift: "వ్యత్యాసం", drift: "వ్యత్యాసం", Seconds: "సెకన్లు", seconds: "సెకన్లు", s: "సె", Mfa: "బహుళ కారక ధృవీకరణ", Risk: "ప్రమాదం", User: "వినియోగదారు", Logout: "లాగ్‌అవుట్" },
  mr: { "Awaiting deployment configuration": "उपयोजन संरचनेची प्रतीक्षा", Drift: "फरक", drift: "फरक", Seconds: "सेकंद", seconds: "सेकंद", s: "से", Mfa: "बहु-घटक प्रमाणीकरण", Risk: "जोखीम", User: "वापरकर्ता", Logout: "लॉगआउट" },
};

const dynamicRecordTerms: DomainLocalizations = {
  en: {},
  hi: { Masked: "गुमनाम किया गया", masked: "गुमनाम किया गया", Digitized: "डिजिटाइज़ किया गया", Scanned: "स्कैन किया गया", Validated: "सत्यापित", PM: "अपराह्न", pm: "अपराह्न", AM: "पूर्वाह्न", am: "पूर्वाह्न", Ppm: "पृष्ठ प्रति मिनट", ppm: "पृष्ठ प्रति मिनट", KB: "केबी", MB: "एमबी", GB: "जीबी", DPI: "डीपीआई" },
  kn: { Masked: "ಅನಾಮಧೇಯಗೊಳಿಸಲಾಗಿದೆ", masked: "ಅನಾಮಧೇಯಗೊಳಿಸಲಾಗಿದೆ", Digitized: "ಡಿಜಿಟಲೀಕರಿಸಲಾಗಿದೆ", Scanned: "ಸ್ಕ್ಯಾನ್ ಮಾಡಲಾಗಿದೆ", Validated: "ಮೌಲ್ಯೀಕರಿಸಲಾಗಿದೆ", PM: "ಅಪರಾಹ್ನ", pm: "ಅಪರಾಹ್ನ", AM: "ಪೂರ್ವಾಹ್ನ", am: "ಪೂರ್ವಾಹ್ನ", Ppm: "ನಿಮಿಷಕ್ಕೆ ಪುಟಗಳು", ppm: "ನಿಮಿಷಕ್ಕೆ ಪುಟಗಳು", KB: "ಕೆಬಿ", MB: "ಎಂಬಿ", GB: "ಜಿಬಿ", DPI: "ಡಿಪಿಐ" },
  ta: { Masked: "அநாமதேயமாக்கப்பட்டது", masked: "அநாமதேயமாக்கப்பட்டது", Digitized: "எண்மயமாக்கப்பட்டது", Scanned: "வருடப்பட்டது", Validated: "சரிபார்க்கப்பட்டது", PM: "பிற்பகல்", pm: "பிற்பகல்", AM: "முற்பகல்", am: "முற்பகல்", Ppm: "நிமிடத்திற்குப் பக்கங்கள்", ppm: "நிமிடத்திற்குப் பக்கங்கள்", KB: "கேபி", MB: "எம்பி", GB: "ஜிபி", DPI: "டிபிஐ" },
  te: { Masked: "అజ్ఞాతీకరించబడింది", masked: "అజ్ఞాతీకరించబడింది", Digitized: "డిజిటలీకరించబడింది", Scanned: "స్కాన్ చేయబడింది", Validated: "ధృవీకరించబడింది", PM: "అపరాహ్నం", pm: "అపరాహ్నం", AM: "పూర్వాహ్నం", am: "పూర్వాహ్నం", Ppm: "నిమిషానికి పేజీలు", ppm: "నిమిషానికి పేజీలు", KB: "కేబీ", MB: "ఎంబీ", GB: "జీబీ", DPI: "డీపీఐ" },
  mr: { Masked: "अनामिक केले", masked: "अनामिक केले", Digitized: "डिजिटाइझ केले", Scanned: "स्कॅन केले", Validated: "सत्यापित", PM: "दुपारनंतर", pm: "दुपारनंतर", AM: "दुपारपूर्व", am: "दुपारपूर्व", Ppm: "पृष्ठे प्रति मिनिट", ppm: "पृष्ठे प्रति मिनिट", KB: "केबी", MB: "एमबी", GB: "जीबी", DPI: "डीपीआय" },
};

for (const language of Object.keys(domainExtras) as LanguageCode[]) {
  Object.assign(domainLocalizations[language], domainExtras[language], dynamicRecordTerms[language]);
}
