// import type { LanguageCode } from "@/i18n/client";

// type RecordLocalizations = Record<LanguageCode, Record<string, string>>;

// /** Localized human-readable values returned by the demo/reference APIs. */
// export const recordLocalizations: RecordLocalizations = {
//   en: {},
//   hi: {
//     "Northbridge University": "नॉर्थब्रिज विश्वविद्यालय", "November 2026 End Semester": "नवंबर 2026 अंतिम सेमेस्टर", "November 2026 Central Evaluation Camp": "नवंबर 2026 केंद्रीय मूल्यांकन शिविर", "Northbridge Central Evaluation Centre": "नॉर्थब्रिज केंद्रीय मूल्यांकन केंद्र",
//     "B.Tech Computer Science": "बी.टेक कंप्यूटर विज्ञान", "Computer Science": "कंप्यूटर विज्ञान", "Distributed Systems": "वितरित प्रणालियाँ", "Applied Machine Learning": "अनुप्रयुक्त मशीन लर्निंग", "Database Management Systems": "डेटाबेस प्रबंधन प्रणालियाँ", "Probability and Statistics": "प्रायिकता और सांख्यिकी",
//     "Dr. Kavya Rao": "डॉ. काव्या राव", "Dr. Meera Iyer": "डॉ. मीरा अय्यर", "Dr. Neha Pillai": "डॉ. नेहा पिल्लै", "Prof. Arjun Das": "प्रो. अर्जुन दास", "Prof. Imran Khan": "प्रो. इमरान खान", "Arjun Das": "अर्जुन दास", "Imran Khan": "इमरान खान", "Kavya Rao": "काव्या राव", "Meera Iyer": "मीरा अय्यर", "Neha Pillai": "नेहा पिल्लै", "Asha Menon": "आशा मेनन", "Exam Controller": "परीक्षा नियंत्रक", "Script receiver": "उत्तरपुस्तिका प्राप्तकर्ता", "Scanner operator": "स्कैनर संचालक", "Chain custody officer": "अभिरक्षा श्रृंखला अधिकारी", "Mask Reviewer": "मास्क समीक्षक", "Mask Verifier": "मास्क सत्यापनकर्ता", "Internal Auditor": "आंतरिक लेखा परीक्षक", "Platform Administrator": "प्लेटफ़ॉर्म प्रशासक",
//     "Associate Professor": "सह-प्राध्यापक", Professor: "प्राध्यापक", PhD: "पीएचडी", "Central duplex scanner": "केंद्रीय डुप्लेक्स स्कैनर", "Distributed intake scanner": "वितरित प्राप्ति स्कैनर", "Exam script quality profile": "परीक्षा उत्तरपुस्तिका गुणवत्ता प्रोफ़ाइल",
//     "Digitization Hall A": "डिजिटलीकरण कक्ष ए", "Evaluation Centre B": "मूल्यांकन केंद्र बी", "Examination Centre A": "परीक्षा केंद्र ए", "Examination Centre B": "परीक्षा केंद्र बी", "Examination Centre C": "परीक्षा केंद्र सी", "Examination Centre D": "परीक्षा केंद्र डी", "Digital Repository A": "डिजिटल भंडार ए", "Manual intake queue": "मैनुअल प्राप्ति कतार", "Academic Block C": "शैक्षणिक खंड सी", "Odd semester": "विषम सेमेस्टर",
//     "University ERP Result Gateway": "विश्वविद्यालय ईआरपी परिणाम गेटवे", "Primary regional recovery plan": "प्राथमिक क्षेत्रीय पुनर्प्राप्ति योजना", "northbridge-university": "नॉर्थब्रिज-विश्वविद्यालय", "Physical count differs from dispatch manifest.": "भौतिक गणना प्रेषण सूची से भिन्न है।", "Daily opening controls verified.": "दैनिक प्रारंभिक नियंत्रण सत्यापित किए गए।", "Verified local development evaluator": "स्थानीय विकास मूल्यांकनकर्ता सत्यापित", "Approved local development evaluator": "स्थानीय विकास मूल्यांकनकर्ता स्वीकृत", "Award marks against the published criterion evidence. Record zero-mark and unanswered outcomes explicitly.": "प्रकाशित मानदंड साक्ष्य के अनुसार अंक दें। शून्य-अंक और अनुत्तरित परिणाम स्पष्ट रूप से दर्ज करें।",
//   },
//   kn: {
//     "Northbridge University": "ನಾರ್ತ್‌ಬ್ರಿಡ್ಜ್ ವಿಶ್ವವಿದ್ಯಾಲಯ", "November 2026 End Semester": "ನವೆಂಬರ್ 2026 ಅಂತಿಮ ಸೆಮಿಸ್ಟರ್", "November 2026 Central Evaluation Camp": "ನವೆಂಬರ್ 2026 ಕೇಂದ್ರೀಯ ಮೌಲ್ಯಮಾಪನ ಶಿಬಿರ", "Northbridge Central Evaluation Centre": "ನಾರ್ತ್‌ಬ್ರಿಡ್ಜ್ ಕೇಂದ್ರೀಯ ಮೌಲ್ಯಮಾಪನ ಕೇಂದ್ರ",
//     "B.Tech Computer Science": "ಬಿ.ಟೆಕ್ ಕಂಪ್ಯೂಟರ್ ವಿಜ್ಞಾನ", "Computer Science": "ಕಂಪ್ಯೂಟರ್ ವಿಜ್ಞಾನ", "Distributed Systems": "ವಿತರಿತ ವ್ಯವಸ್ಥೆಗಳು", "Applied Machine Learning": "ಅನ್ವಯಿಕ ಯಂತ್ರ ಕಲಿಕೆ", "Database Management Systems": "ದತ್ತಸಂಚಯ ನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆಗಳು", "Probability and Statistics": "ಸಂಭವನೀಯತೆ ಮತ್ತು ಸಂಖ್ಯಾಶಾಸ್ತ್ರ",
//     "Dr. Kavya Rao": "ಡಾ. ಕಾವ್ಯ ರಾವ್", "Dr. Meera Iyer": "ಡಾ. ಮೀರಾ ಅಯ್ಯರ್", "Dr. Neha Pillai": "ಡಾ. ನೇಹಾ ಪಿಳ್ಳೈ", "Prof. Arjun Das": "ಪ್ರೊ. ಅರ್ಜುನ್ ದಾಸ್", "Prof. Imran Khan": "ಪ್ರೊ. ಇಮ್ರಾನ್ ಖಾನ್", "Arjun Das": "ಅರ್ಜುನ್ ದಾಸ್", "Imran Khan": "ಇಮ್ರಾನ್ ಖಾನ್", "Kavya Rao": "ಕಾವ್ಯ ರಾವ್", "Meera Iyer": "ಮೀರಾ ಅಯ್ಯರ್", "Neha Pillai": "ನೇಹಾ ಪಿಳ್ಳೈ", "Asha Menon": "ಆಶಾ ಮೆನನ್", "Exam Controller": "ಪರೀಕ್ಷಾ ನಿಯಂತ್ರಕ", "Script receiver": "ಉತ್ತರಪತ್ರಿಕೆ ಸ್ವೀಕರಿಸುವವರು", "Scanner operator": "ಸ್ಕ್ಯಾನರ್ ನಿರ್ವಾಹಕ", "Chain custody officer": "ಅಭಿರಕ್ಷಾ ಸರಪಳಿ ಅಧಿಕಾರಿ", "Mask Reviewer": "ಮಾಸ್ಕ್ ಪರಿಶೀಲಕ", "Mask Verifier": "ಮಾಸ್ಕ್ ದೃಢೀಕರಣಕಾರ", "Internal Auditor": "ಆಂತರಿಕ ಲೆಕ್ಕಪರಿಶೋಧಕ", "Platform Administrator": "ವೇದಿಕೆ ನಿರ್ವಾಹಕ",
//     "Associate Professor": "ಸಹ ಪ್ರಾಧ್ಯಾಪಕ", Professor: "ಪ್ರಾಧ್ಯಾಪಕ", PhD: "ಪಿಎಚ್‌ಡಿ", "Central duplex scanner": "ಕೇಂದ್ರೀಯ ಡ್ಯುಪ್ಲೆಕ್ಸ್ ಸ್ಕ್ಯಾನರ್", "Distributed intake scanner": "ವಿತರಿತ ಸ್ವೀಕೃತಿ ಸ್ಕ್ಯಾನರ್", "Exam script quality profile": "ಪರೀಕ್ಷಾ ಉತ್ತರಪತ್ರಿಕೆ ಗುಣಮಟ್ಟ ಪ್ರೊಫೈಲ್",
//     "Digitization Hall A": "ಡಿಜಿಟಲೀಕರಣ ಸಭಾಂಗಣ ಎ", "Evaluation Centre B": "ಮೌಲ್ಯಮಾಪನ ಕೇಂದ್ರ ಬಿ", "Examination Centre A": "ಪರೀಕ್ಷಾ ಕೇಂದ್ರ ಎ", "Examination Centre B": "ಪರೀಕ್ಷಾ ಕೇಂದ್ರ ಬಿ", "Examination Centre C": "ಪರೀಕ್ಷಾ ಕೇಂದ್ರ ಸಿ", "Examination Centre D": "ಪರೀಕ್ಷಾ ಕೇಂದ್ರ ಡಿ", "Digital Repository A": "ಡಿಜಿಟಲ್ ಭಂಡಾರ ಎ", "Manual intake queue": "ಹಸ್ತಚಾಲಿತ ಸ್ವೀಕೃತಿ ಸರತಿ", "Academic Block C": "ಶೈಕ್ಷಣಿಕ ಬ್ಲಾಕ್ ಸಿ", "Odd semester": "ಬೆಸ ಸೆಮಿಸ್ಟರ್",
//     "University ERP Result Gateway": "ವಿಶ್ವವಿದ್ಯಾಲಯ ಇಆರ್‌ಪಿ ಫಲಿತಾಂಶ ಗೇಟ್‌ವೇ", "Primary regional recovery plan": "ಪ್ರಾಥಮಿಕ ಪ್ರಾದೇಶಿಕ ಮರುಪಡೆಯುವಿಕೆ ಯೋಜನೆ", "northbridge-university": "ನಾರ್ತ್‌ಬ್ರಿಡ್ಜ್-ವಿಶ್ವವಿದ್ಯಾಲಯ", "Physical count differs from dispatch manifest.": "ಭೌತಿಕ ಎಣಿಕೆಯು ರವಾನೆ ಪಟ್ಟಿಯಿಂದ ಭಿನ್ನವಾಗಿದೆ.", "Daily opening controls verified.": "ದೈನಂದಿನ ಆರಂಭಿಕ ನಿಯಂತ್ರಣಗಳನ್ನು ಪರಿಶೀಲಿಸಲಾಗಿದೆ.", "Verified local development evaluator": "ಸ್ಥಳೀಯ ಅಭಿವೃದ್ಧಿ ಮೌಲ್ಯಮಾಪಕರನ್ನು ಪರಿಶೀಲಿಸಲಾಗಿದೆ", "Approved local development evaluator": "ಸ್ಥಳೀಯ ಅಭಿವೃದ್ಧಿ ಮೌಲ್ಯಮಾಪಕರನ್ನು ಅನುಮೋದಿಸಲಾಗಿದೆ", "Award marks against the published criterion evidence. Record zero-mark and unanswered outcomes explicitly.": "ಪ್ರಕಟಿತ ಮಾನದಂಡದ ಸಾಕ್ಷ್ಯದ ಆಧಾರದಲ್ಲಿ ಅಂಕಗಳನ್ನು ನೀಡಿ. ಶೂನ್ಯ ಅಂಕ ಮತ್ತು ಉತ್ತರಿಸದ ಫಲಿತಾಂಶಗಳನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ದಾಖಲಿಸಿ.",
//   },
//   ta: {
//     "Northbridge University": "நார்த்பிரிட்ஜ் பல்கலைக்கழகம்", "November 2026 End Semester": "நவம்பர் 2026 இறுதிப் பருவம்", "November 2026 Central Evaluation Camp": "நவம்பர் 2026 மத்திய மதிப்பீட்டு முகாம்", "Northbridge Central Evaluation Centre": "நார்த்பிரிட்ஜ் மத்திய மதிப்பீட்டு மையம்",
//     "B.Tech Computer Science": "பி.டெக் கணினி அறிவியல்", "Computer Science": "கணினி அறிவியல்", "Distributed Systems": "பகிர்ந்தளிக்கப்பட்ட அமைப்புகள்", "Applied Machine Learning": "பயன்பாட்டு இயந்திரக் கற்றல்", "Database Management Systems": "தரவுத்தள மேலாண்மை அமைப்புகள்", "Probability and Statistics": "நிகழ்தகவு மற்றும் புள்ளியியல்",
//     "Dr. Kavya Rao": "டாக்டர் காவ்யா ராவ்", "Dr. Meera Iyer": "டாக்டர் மீரா ஐயர்", "Dr. Neha Pillai": "டாக்டர் நேஹா பிள்ளை", "Prof. Arjun Das": "பேரா. அர்ஜுன் தாஸ்", "Prof. Imran Khan": "பேரா. இம்ரான் கான்", "Arjun Das": "அர்ஜுன் தாஸ்", "Imran Khan": "இம்ரான் கான்", "Kavya Rao": "காவ்யா ராவ்", "Meera Iyer": "மீரா ஐயர்", "Neha Pillai": "நேஹா பிள்ளை", "Asha Menon": "ஆஷா மேனன்", "Exam Controller": "தேர்வுக் கட்டுப்பாட்டாளர்", "Script receiver": "விடைத்தாள் பெறுநர்", "Scanner operator": "வருடி இயக்குநர்", "Chain custody officer": "பாதுகாப்புச் சங்கிலி அலுவலர்", "Mask Reviewer": "மறைப்பாய்வாளர்", "Mask Verifier": "மறைப்பு சரிபார்ப்பாளர்", "Internal Auditor": "உள் தணிக்கையாளர்", "Platform Administrator": "தள நிர்வாகி",
//     "Associate Professor": "இணைப் பேராசிரியர்", Professor: "பேராசிரியர்", PhD: "முனைவர் பட்டம்", "Central duplex scanner": "மத்திய இருபக்க வருடி", "Distributed intake scanner": "பகிர்ந்தளிக்கப்பட்ட வரவு வருடி", "Exam script quality profile": "தேர்வு விடைத்தாள் தரச் சுயவிவரம்",
//     "Digitization Hall A": "டிஜிட்டலாக்க அரங்கம் ஏ", "Evaluation Centre B": "மதிப்பீட்டு மையம் பி", "Examination Centre A": "தேர்வு மையம் ஏ", "Examination Centre B": "தேர்வு மையம் பி", "Examination Centre C": "தேர்வு மையம் சி", "Examination Centre D": "தேர்வு மையம் டி", "Digital Repository A": "டிஜிட்டல் களஞ்சியம் ஏ", "Manual intake queue": "கைமுறை வரவு வரிசை", "Academic Block C": "கல்வித் தொகுதி சி", "Odd semester": "ஒற்றைப் பருவம்",
//     "University ERP Result Gateway": "பல்கலைக்கழக ஈஆர்பி முடிவு நுழைவாயில்", "Primary regional recovery plan": "முதன்மை பிராந்திய மீட்புத் திட்டம்", "northbridge-university": "நார்த்பிரிட்ஜ்-பல்கலைக்கழகம்", "Physical count differs from dispatch manifest.": "நேரடி எண்ணிக்கை அனுப்புகைப் பட்டியலிலிருந்து வேறுபடுகிறது.", "Daily opening controls verified.": "தினசரி தொடக்கக் கட்டுப்பாடுகள் சரிபார்க்கப்பட்டன.", "Verified local development evaluator": "உள்ளூர் மேம்பாட்டு மதிப்பீட்டாளர் சரிபார்க்கப்பட்டார்", "Approved local development evaluator": "உள்ளூர் மேம்பாட்டு மதிப்பீட்டாளர் அங்கீகரிக்கப்பட்டார்", "Award marks against the published criterion evidence. Record zero-mark and unanswered outcomes explicitly.": "வெளியிடப்பட்ட அளவுகோல் சான்றின் அடிப்படையில் மதிப்பெண்கள் வழங்கவும். பூஜ்ய மதிப்பெண் மற்றும் பதிலளிக்காத முடிவுகளைத் தெளிவாகப் பதிவு செய்யவும்.",
//   },
//   te: {
//     "Northbridge University": "నార్త్‌బ్రిడ్జ్ విశ్వవిద్యాలయం", "November 2026 End Semester": "నవంబర్ 2026 చివరి సెమిస్టర్", "November 2026 Central Evaluation Camp": "నవంబర్ 2026 కేంద్ర మూల్యాంకన శిబిరం", "Northbridge Central Evaluation Centre": "నార్త్‌బ్రిడ్జ్ కేంద్ర మూల్యాంకన కేంద్రం",
//     "B.Tech Computer Science": "బి.టెక్ కంప్యూటర్ సైన్స్", "Computer Science": "కంప్యూటర్ సైన్స్", "Distributed Systems": "పంపిణీ వ్యవస్థలు", "Applied Machine Learning": "అనువర్తిత యంత్ర అభ్యాసం", "Database Management Systems": "డేటాబేస్ నిర్వహణ వ్యవస్థలు", "Probability and Statistics": "సంభావ్యత మరియు గణాంకాలు",
//     "Dr. Kavya Rao": "డా. కావ్య రావు", "Dr. Meera Iyer": "డా. మీరా అయ్యర్", "Dr. Neha Pillai": "డా. నేహా పిళ్లై", "Prof. Arjun Das": "ప్రొ. అర్జున్ దాస్", "Prof. Imran Khan": "ప్రొ. ఇమ్రాన్ ఖాన్", "Arjun Das": "అర్జున్ దాస్", "Imran Khan": "ఇమ్రాన్ ఖాన్", "Kavya Rao": "కావ్య రావు", "Meera Iyer": "మీరా అయ్యర్", "Neha Pillai": "నేహా పిళ్లై", "Asha Menon": "ఆశా మేనన్", "Exam Controller": "పరీక్ష నియంత్రకుడు", "Script receiver": "జవాబుపత్రాల స్వీకర్త", "Scanner operator": "స్కానర్ నిర్వాహకుడు", "Chain custody officer": "అభిరక్షణ శ్రేణి అధికారి", "Mask Reviewer": "మాస్క్ సమీక్షకుడు", "Mask Verifier": "మాస్క్ ధృవీకర్త", "Internal Auditor": "అంతర్గత ఆడిటర్", "Platform Administrator": "వేదిక నిర్వాహకుడు",
//     "Associate Professor": "సహ ఆచార్యుడు", Professor: "ఆచార్యుడు", PhD: "పీహెచ్‌డీ", "Central duplex scanner": "కేంద్ర ద్విముఖ స్కానర్", "Distributed intake scanner": "పంపిణీ స్వీకరణ స్కానర్", "Exam script quality profile": "పరీక్ష జవాబు పత్ర నాణ్యత ప్రొఫైల్",
//     "Digitization Hall A": "డిజిటైజేషన్ హాల్ ఏ", "Evaluation Centre B": "మూల్యాంకన కేంద్రం బి", "Examination Centre A": "పరీక్ష కేంద్రం ఏ", "Examination Centre B": "పరీక్ష కేంద్రం బి", "Examination Centre C": "పరీక్ష కేంద్రం సి", "Examination Centre D": "పరీక్ష కేంద్రం డి", "Digital Repository A": "డిజిటల్ భాండాగారం ఏ", "Manual intake queue": "మాన్యువల్ స్వీకరణ క్యూ", "Academic Block C": "విద్యా విభాగం సి", "Odd semester": "బేసి సెమిస్టర్",
//     "University ERP Result Gateway": "విశ్వవిద్యాలయ ఈఆర్‌పీ ఫలిత గేట్‌వే", "Primary regional recovery plan": "ప్రాథమిక ప్రాంతీయ పునరుద్ధరణ ప్రణాళిక", "northbridge-university": "నార్త్‌బ్రిడ్జ్-విశ్వవిద్యాలయం", "Physical count differs from dispatch manifest.": "భౌతిక లెక్క రవాణా జాబితాతో భిన్నంగా ఉంది.", "Daily opening controls verified.": "రోజువారీ ప్రారంభ నియంత్రణలు ధృవీకరించబడ్డాయి.", "Verified local development evaluator": "స్థానిక అభివృద్ధి మూల్యాంకనకర్త ధృవీకరించబడ్డారు", "Approved local development evaluator": "స్థానిక అభివృద్ధి మూల్యాంకనకర్త ఆమోదించబడ్డారు", "Award marks against the published criterion evidence. Record zero-mark and unanswered outcomes explicitly.": "ప్రచురించిన ప్రమాణ సాక్ష్యానికి అనుగుణంగా మార్కులు ఇవ్వండి. సున్నా మార్కులు మరియు సమాధానం లేని ఫలితాలను స్పష్టంగా నమోదు చేయండి.",
//   },
//   mr: {
//     "Northbridge University": "नॉर्थब्रिज विद्यापीठ", "November 2026 End Semester": "नोव्हेंबर 2026 अंतिम सत्र", "November 2026 Central Evaluation Camp": "नोव्हेंबर 2026 केंद्रीय मूल्यमापन शिबिर", "Northbridge Central Evaluation Centre": "नॉर्थब्रिज केंद्रीय मूल्यमापन केंद्र",
//     "B.Tech Computer Science": "बी.टेक संगणक विज्ञान", "Computer Science": "संगणक विज्ञान", "Distributed Systems": "वितरित प्रणाली", "Applied Machine Learning": "उपयोजित यंत्र शिक्षण", "Database Management Systems": "डेटाबेस व्यवस्थापन प्रणाली", "Probability and Statistics": "संभाव्यता आणि सांख्यिकी",
//     "Dr. Kavya Rao": "डॉ. काव्या राव", "Dr. Meera Iyer": "डॉ. मीरा अय्यर", "Dr. Neha Pillai": "डॉ. नेहा पिल्लई", "Prof. Arjun Das": "प्रा. अर्जुन दास", "Prof. Imran Khan": "प्रा. इमरान खान", "Arjun Das": "अर्जुन दास", "Imran Khan": "इमरान खान", "Kavya Rao": "काव्या राव", "Meera Iyer": "मीरा अय्यर", "Neha Pillai": "नेहा पिल्लई", "Asha Menon": "आशा मेनन", "Exam Controller": "परीक्षा नियंत्रक", "Script receiver": "उत्तरपत्रिका स्वीकारकर्ता", "Scanner operator": "स्कॅनर चालक", "Chain custody officer": "अभिरक्षा साखळी अधिकारी", "Mask Reviewer": "मास्क पुनरावलोकक", "Mask Verifier": "मास्क पडताळक", "Internal Auditor": "अंतर्गत लेखापरीक्षक", "Platform Administrator": "मंच प्रशासक",
//     "Associate Professor": "सहयोगी प्राध्यापक", Professor: "प्राध्यापक", PhD: "पीएचडी", "Central duplex scanner": "केंद्रीय द्विमुखी स्कॅनर", "Distributed intake scanner": "वितरित स्वीकृती स्कॅनर", "Exam script quality profile": "परीक्षा उत्तरपत्रिका गुणवत्ता प्रोफाइल",
//     "Digitization Hall A": "डिजिटायझेशन सभागृह ए", "Evaluation Centre B": "मूल्यमापन केंद्र बी", "Examination Centre A": "परीक्षा केंद्र ए", "Examination Centre B": "परीक्षा केंद्र बी", "Examination Centre C": "परीक्षा केंद्र सी", "Examination Centre D": "परीक्षा केंद्र डी", "Digital Repository A": "डिजिटल भांडार ए", "Manual intake queue": "हस्तचलित स्वीकृती रांग", "Academic Block C": "शैक्षणिक विभाग सी", "Odd semester": "विषम सत्र",
//     "University ERP Result Gateway": "विद्यापीठ ईआरपी निकाल प्रवेशद्वार", "Primary regional recovery plan": "प्राथमिक प्रादेशिक पुनर्प्राप्ती योजना", "northbridge-university": "नॉर्थब्रिज-विद्यापीठ", "Physical count differs from dispatch manifest.": "प्रत्यक्ष संख्या पाठवणी सूचीपेक्षा वेगळी आहे.", "Daily opening controls verified.": "दैनंदिन प्रारंभिक नियंत्रणे पडताळली आहेत.", "Verified local development evaluator": "स्थानिक विकास मूल्यमापकाची पडताळणी झाली", "Approved local development evaluator": "स्थानिक विकास मूल्यमापक मंजूर झाला", "Award marks against the published criterion evidence. Record zero-mark and unanswered outcomes explicitly.": "प्रकाशित निकष पुराव्यानुसार गुण द्या. शून्य गुण आणि अनुत्तरित निकाल स्पष्टपणे नोंदवा.",
//   },
// };
